### ISSUE TITLE
Remove Gravatar or make it optional

### ISSUE THREAD

**Issue by shaaati** [nitely/Spirit#103]
Using Gravatar can risk the privacy of your users (see [here](http://www.developer.it/post/gravatars-why-publishing-your-email-s-hash-is-not-a-good-idea) for more info).

Therefore, it would be a good idea to either remove it or at least make it optional, so that admins can decide whether or not they want it.

**Comment by nitely** [comment]
Once background tasks (ie: celery) is in place, avatars will be fetched and
stored in the server.

**Comment by shaaati** [comment]
Sounds great, is there an estimated timeline?

**Comment by nitely** [comment]
Nop

2016-02-18 13:36 GMT-03:00 shaaati <notifications@github.com>:
