### ISSUE TITLE
Remove 3000 character comment limit

### ISSUE THREAD

**Issue by sirex** [nitely/Spirit#107]
Please remove 3000 character limit in comments.

For example this mid-size tutorial consists of more than 8000 characters:
https://ubuntu.lt/topic/7630/naujokams-%C4%AFsidiegus-ubuntu/

**Comment by nitely** [comment]
There must be some limit, otherwise a malicious user could send a bazillion characters.

I just added `ST_COMMENT_MAX_LEN` to settings, just increase it to what you consider an appropriate limit.

**Comment by sirex** [comment]
Thanks, that solves the issue. Since comment length restriction has been moved from model field to form field, I can freely change it without needing to create database migration.
