### ISSUE TITLE
Spirit as an Django app for an existing project

### ISSUE THREAD

**Issue by lerrua** [nitely/Spirit#109]
Hi guys,

I Have a question. I need a forum for my Django project, is Spirit compatible with legacy Django projects or it's just a standalone project?

**Comment by nitely** [comment]
It can be integrated to an existing project, as long as it's [compatible](https://github.com/nitely/Spirit#compatibility) with the current requirements.

**Comment by lerrua** [comment]
thanks for the answer @nitely. I'll try it.
