### ISSUE TITLE
Colors for categories

### ISSUE THREAD

**Issue by sheepsy90** [nitely/Spirit#110]
In order to better distinguish between posts it would be great if categories could be assigned with colours and then sued in the overview.

**Comment by sheepsy90** [comment]
If i am going to use this software for my forum I will definitely look into that possibility

**Comment by sheepsy90** [comment]
Steps to accomplish this:
* add a colour field in the model that represents the category
* make it editable in the management for categories
* use the information in the template rendering to nicely highlight the category in some way

**Comment by sheepsy90** [comment]
@nitely Is that something that is appropriate?

![screenshot from 2016-04-23 21 52 58](https://cloud.githubusercontent.com/assets/595087/14763706/edb559e2-099d-11e6-9e16-46c7c2527a1c.png)

**Comment by nitely** [comment]
It's better to color out the category title, IMHO, less noise. The model field should be nullable (as in optional) so color is not required.

Also, as an enhancement, it'd be nice to have a color picker, just like the one here in github when chosing a label color. But don't worry about it, I'll add it later this year when I re-do the UI.

**Comment by sheepsy90** [comment]
The nullable is a good point. I did not thought of that but rather always assigned the default colour being white. 

I would still prefer the colour being used as a way to easily spot which category a topic has so I would like to leave it at the left side. With less dominant colours it would then be less noise anyway.

I looked into the colour picker but I am not super confident to implement it in an appropriate way so I would leave that right now and just have a simple text field. As you mentioned a colour picker can be implemented at the point where the UI is being refactored.

**Comment by nitely** [comment]
> I would still prefer the colour being used as a way to easily spot which category a topic has so I would like to leave it at the left side. With less dominant colours it would then be less noise anyway.

It would, it adds up. You can always override the template, though.

Also, in the future there will likely be the user's avatar in that place, the reason I haven't done that yet is coz of gravatar.

**Comment by sheepsy90** [comment]
@nitely Can you review the code and give me some tips if I made something odd ;)

Thanks :)

**Comment by nitely** [comment]
Nice job!

> Can you review the code and give me some tips if I made something odd ;)

Yep, I will do it within the commit.

**Comment by nitely** [comment]
Fixed by #112
