### ISSUE TITLE
i18n in url patterns

### ISSUE THREAD

**Issue by a-olszewski** [nitely/Spirit#122]
what about this?

**Comment by nitely** [comment]
So anonym users can change the display language? or what for?

**Comment by a-olszewski** [comment]
It could be. But also it's for consistence in urls translations. What about sites that uses django-spirit just as a part of a project?

**Comment by nitely** [comment]
> But also it's for consistence in urls translations.

Then no. Posts will be in whatever the main languages is, so it's does not makes much sense.

**Comment by a-olszewski** [comment]
so: 
/forumas/topic/1/teskt-šia-kalba/
/форум/topis/publish/
etc is ok? :)

**Comment by nitely** [comment]
That is ok. You can already do that.

**Comment by a-olszewski** [comment]
ok thanks :)
