### ISSUE TITLE
nginx

### ISSUE THREAD

**Issue by patatetom** [nitely/Spirit#127]
hi,
I follow your _small_ documentation and everything is ok for installation and runtest, but I'm trying to run spirit behind nginx with proxy_pass and all under /static/ (css, js) is missing : could you explain the good relation to build between nginx and spirit/django ?
thanks

nginx.conf :
`location /spirit/ { proxy_pass http://localhost:8000/; }`

**Comment by nitely** [comment]
You should also define static routes, like this:

```
location /static {
    alias /home/Spirit/spirit/static;
}
		
location /media {
    alias /home/Spirit/media;
}
```

If you have further questions, ask them in the django user mailing list, or some nginx community, since this has nothing to do with Spirit.

**Comment by patatetom** [comment]
thanks
