### ISSUE TITLE
Uploading large images fails silently

### ISSUE THREAD

**Issue by ElessarWebb** [nitely/Spirit#132]
It seems that small image uploads works fine, but when I select something very large it just results in a comment that says `uploading DSC_6922.JPG`, nothing logged, nothing noticeable on the client (but a failed API call to `comments/upload`)

**Comment by nitely** [comment]
> [...] but a failed API call to comments/upload

What status code does the server returns? Does the response has a payload? this is very likely related to your server configuration.

Can you try this in the [Spirit comunity](http://community.spirit-project.com/category/8/)?

I tried it and the server (nginx) just closes the connection, the comment box shows `![error: error ]()`. The (nginx) error log shows `2016/07/21 15:30:27 [error] 10#0: *XXXX client intended to send too large body: 3736318 bytes`.
