### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by fdik** [nitely/Spirit#138]
Hi,

in django we usually have projectdir/appdir as structure. Then we have a local_settings.py in appdir.

How do I get this structure with Spirit? I checked out the example. But there the directory with settings.py is not a subdirectory of the one with manage.py, hence breaking django's concept of apps in projects.

Also I was trying to find a way not using example project. Therefore, I was search if there is a project template, which can be cloned using django-admin. I did not manage to get there. Is there a way to do that?

Yours,
VB.

**Comment by nitely** [comment]
> How do I get this structure with Spirit?

Setup your django project as usual, then pip install spirit and add it to your installed apps as any other django app.

There is nothing special about Spirit, it's just a django app.

> Also I was trying to find a way not using example project. Therefore, I was search if there is a project template, which can be cloned using django-admin. I did not manage to get there. Is there a way to do that?

No, but having a command such as `spirit start myproject` that setups the project directoy layout would be really cool.

**Comment by fdik** [comment]
My question is, how to add it as a django app?

Usually, I'm just copying the directory with settings.py in. In this case, there seems to be even no settings.py (?)

What is the recommended way to add it as an app to an existing project?

**Comment by nitely** [comment]
> My question is, how to add it as a django app?

There are two ways: 1. import the spirit [settings](https://github.com/nitely/Spirit/blob/master/spirit/settings.py) (see the example and [spirit-heroku](https://github.com/nitely/spirit-heroku)) 2. add all the settings manually.

> Usually, I'm just copying the directory with settings.py in. In this case, there seems to be even no settings.py (?)

That's coz Spirit *is not a project* but an app.

> What is the recommended way to add it as an app to an existing project?

For a project that *has other apps*, I think the best way is to (manually) [add everything spirit requires](https://github.com/nitely/Spirit/blob/master/spirit/settings.py) to the main settings.py as you would do with any other app.

My previous comment was a bit oversimplified since it requires a lot of settings not just adding it to the installed apps :smile:

**Comment by fdik** [comment]
I saw the `from spirit.settings import *` in settings/base.py. Probably this is answering the question.

Got a copy running. But I have the problem of getting

`django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'st_rate_limit' in settings.CACHES`

when doing any POST. I will test with `ST_RATELIMIT_CACHE = None` Hope that helps.

Last question: is there any documentation you can point me to, please?

**Comment by nitely** [comment]
It seems [st_rate_limit](https://github.com/nitely/Spirit/blob/b133430866790bca026107c65b36493bfce9870d/spirit/settings.py#L97) is missing in your settings.py.

That cache was added in dev (the master branch). I think there's some kind of mismatch of spirit versions here. I recommend to use the latest stable release either through pip or checkout of `v0.4.x` branch. Either clone or pip, pick one of them, don't do both.

> Last question: is there any documentation you can point me to, please?

There are no docs. There is an [upgrading guide](https://github.com/nitely/Spirit/wiki/Upgrading) though.

I usually make docs for everything I release as OSS, but there is not much to document here (I think?). The only stuff that's worth documenting are the installation steps and upgrading steps... for the installation there is the example and for upgrading there is the wiki. Probably once the [hooks](https://github.com/nitely/django-hooks) are implemented I'll make some docs.

**Comment by fdik** [comment]
To be honest: I have no clue how to add it as app. So I copied stuff from example. Probably this gives the mix.

BTW:

`ST_RATELIMIT_CACHE = 'default'` in my `prod_local.py` fixed the error.

**Comment by nitely** [comment]
> I have no clue how to add it as app.

Either add `from spirit.settings import *` to settings.py or copy stuff from [spirit.settings](https://github.com/nitely/Spirit/blob/master/spirit/settings.py). Both are pretty much the same thing, the only difference is the first one you have to `.extend()` everywhere and watchout for overwritting spirit settings, the second option is safer/more explicit.

> ST_RATELIMIT_CACHE = 'default' in my prod_local.py fixed the error.

There should be a warning in the console about the default cache not having `timeout None`.

It seems the `from spirit.settings import *` is importing Spirit stable (latest release) but using Spirit dev (master branch) as app. There is probably a Spirit package installed as a python package (pip) and also a Spirit package as a local package (git clone).

**Comment by fdik** [comment]
I just removed settings/ (which I copied from example), copied settings.py from the package, added `from .local_settings import *` to the ending, then copied my old prod_local.py to local_settings.py

This is ending with a `ImportError: No module named 'project.settings.dev'; 'project.settings' is not a package`

**Comment by fdik** [comment]
I think I will revert to the settings version of the example

**Comment by fdik** [comment]
Thank you for this great piece of software and the help here!

**Comment by nitely** [comment]
> I just removed settings/ (which I copied from example), copied settings.py from the package, added from .local_settings import * to the ending, then copied my old prod_local.py to local_settings.py
> 
> This is ending with a ImportError: No module named 'project.settings.dev'; 'project.settings' is not a package

That should work. You have to also edit the manage.py to import the `project.settings` instead of `project.settings.dev`

**Comment by nitely** [comment]
There's `spirit start myproject` now, and settings can be copied to an existing project.
