### ISSUE TITLE
Color link

### ISSUE THREAD

**Issue by mauriciobaeza** [nitely/Spirit#144]
Hi...

How to change color links?

I found css class row-link in tag **a** into **styles.all.min.css**, but if change color not work.

Thanks in advance.

**Comment by nitely** [comment]
What link? Links within a comment? [here's the file](https://github.com/nitely/Spirit/blob/master/spirit/core/static/spirit/stylesheets/src/elements/_links.scss) then you have to transpile the sass to generate the `styles.all.min.css`, [here are the steps to do it](https://github.com/nitely/Spirit/tree/master/spirit/core/static/spirit/stylesheets/src).

**Comment by nitely** [comment]
But you could also just override the style with your own css file (or css block in the html's head). You would have to override the [_base.html](https://github.com/nitely/Spirit/blob/master/spirit/core/templates/spirit/_base.html)

**Comment by mauriciobaeza** [comment]
All links, my users... not comment...

Thanks... work fine.
