### ISSUE TITLE
italian translation

### ISSUE THREAD

**Issue by andreav** [nitely/Spirit#146]
Hello, I translated spirit in Italian.

I know I would use transifex to submit a translation, but my join request has been pending for a while.

So now I have spirit .po files ready. Could I push them here?
Is there any smart way to import .po files into transifex?

Thank you for your job on spirit!

**Comment by nitely** [comment]
> I know I would use transifex to submit a translation, but my join request has been pending for a while.

Have you asked here or at the forum about that? I usually accept request as long as the user seems trustworthy.

> Is there any smart way to import .po files into transifex?

AFAIK, there is no way.

> So now I have spirit .po files ready. Could I push them here?

Well, since there is no Italian translation yet, I think that should be ok

**Comment by andreav** [comment]
I asked directly on transifex.
So great! I will review the work and push it as soon as possible!

Thank you!
