### ISSUE TITLE
Add support for Django 1.10

### ISSUE THREAD

**Issue by cryptogun** [nitely/Spirit#148]
```
pip3 install django_spirit
Collecting django_spirit
  Downloading django-spirit-0.4.8.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB
Collecting Django<1.9,>=1.8 (from django_spirit)
  Downloading Django-1.8.17-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB
```
Now I have to reinstall Django 1.10 right?
And haystack has already support Django 1.10. [https://github.com/django-haystack/django-haystack/issues/1437](https://github.com/django-haystack/django-haystack/issues/1437)

**Comment by nitely** [comment]
> Now I have to reinstall Django 1.10 right?

No, v0.4.8 does not support Django 1.10. IF you reinstall Django 1.10 then Spirit will break in many ways, mostly coz of haystack I think.

Spirit 0.5.0dev (the master branch) does support Django 1.10. You can use it right now, it's pretty much stable, there is just a few things to get done before releasing it.

**Comment by cryptogun** [comment]
OK. Thanks. I'll try 0.5.0dev.

**Comment by AlleoNET** [comment]
What about Django 1.11 support?

**Comment by nitely** [comment]
> What about Django 1.11 support?

I've added "official" support just now but I did not had to make any changes.

**Comment by nitely** [comment]
v0.5.0 is out! Closing.
