### ISSUE TITLE
openFileDialog takes 7.5s to popup in Chrome

### ISSUE THREAD

**Issue by cryptogun** [nitely/Spirit#152]
Maybe this is a bug of Chrome. In Firefox the image selection dialog pops up right after I click the image button.
And I can't figure it out where to `console.log()` for debugging. Any suggestions?
`Chrome Version 54.0.2840.90 (64-bit)`
`Linux i-dt 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by nitely** [comment]
I'm on Ubuntu and Chrome 55, I can't reproduce this. The file chooser is snappier.

> And I can't figure it out where to console.log() for debugging. Any suggestions?

You could debug it with the chrome tools, the file is called `editor_image_upload.coffee`. But there is not much to debug... the script just triggers a **click** event on a input field... that field is not attached to the document.

**Comment by nitely** [comment]
Possible related to this http://stackoverflow.com/questions/39187857/inputfile-accept-image-open-dialog-so-slow-with-chrome

**Comment by cryptogun** [comment]
Issue still exists after I updated Chrome to the latest version 55.0.2883.87 (64-bit).
Maybe I should wait until this bug fixed by Chrome. Close this issue if you like.

**Comment by nitely** [comment]
The workaround seems ok. There is `settings.ST_ALLOWED_UPLOAD_IMAGE_FORMAT` so it should be straight forward to generate `accept="image/jpeg, image/gif, image/png"`, I'll take a look later.
