### ISSUE TITLE
Notification feature request

### ISSUE THREAD

**Issue by cryptogun** [nitely/Spirit#156]
I suggest:
1. Reply button should add `@ xxx ` into input box while clicked and then focus cursor on input box. 
2. Bold, italic etc buttons also should make input box focused while clicked.
3. Quote should also trigger a mention event ~~besides @ ( and reply later maybe)~~.
4. Notification of new topic replies should be disabled by default to stop spamming unless: 
 - User is the author of the topic;
 - It's a private topic.
5. `bell icon` > `Show all` should be linked to `topic/notification/` not to `topic/notification/unread/`, and make cross reference between this two notification pages.

That would be more user friendly.

**Comment by nitely** [comment]
> 1. Reply button should add @ xxx into input box while clicked and then focus cursor on input box.
> 2. Bold, italic etc buttons also should make input box focused while clicked.

:+1: 

> 3. Quote should also trigger a mention event besides @ ( and reply later maybe).

I agree on quote should be a mention notification. I'm not sure what "reply later maybe" and how would it work?

> 4. Notification of new topic replies should be disabled by default to stop spamming unless:

I'm not sure about this, not even as a user setting. If I've commented on a topic, then I'm now part of the conversation, so I'd like to receive notifications about new comments. Next comment after mine may even be a reply to my comment (not everyone quotes or mention).

What would fix the spamming issue, is an easier way to unsubscribe from a topic. For example a button next to the notification message. Right now the only to do this is to enter the topic a click on the unsubscribe button at the bottom.

> 5. bell icon > Show all should be linked to topic/notification/ not to topic/notification/unread/, and make cross reference between this two notification pages.

I'll have to think about it, but I think I agree. There should be an option to show the unread notification on the full list. I don't remember exactly how it work :sweat_smile:

**Comment by cryptogun** [comment]
> I'm not sure what "reply later maybe"

I mean reply should be a mention notification too if `1.` is implemented later.

> I'd like to receive notifications about new comments.

Sometimes you reply only because you wanna answer to the topic author once. And not much care about what others say. e.g. Twitter. As time goes by you may have to click and unsubscribe all topics.
In fact that's not a big deal especially for small forum, and more notification improves user stickiness. So far so good.
6. In notification list, mentions should be listed before new reply notifications because mentions are more important/relevant.
> Next comment after mine may even be a reply to my comment (not everyone quotes or mention).

No if `1.` is implemented.
I'd like to make some PRs but I don't have time now. Have to make a living first. And it's time consuming to maintain both self (production) copy and contribution copy. And it seems that it's not able to choose a subset of all commits for pull request on GitHub.

**Comment by nitely** [comment]
> I mean reply should be a mention notification too if 1. is implemented later.

:+1: 

> Sometimes you reply only because you wanna answer to the topic author once. And not much care about what others say. e.g. Twitter. As time goes by you may have to click and unsubscribe all topics.
In fact that's not a big deal especially for small forum, and more notification improves user stickiness. So far so good.

Well, in my experience if you are getting spamming by too many comments, you just hit the unsubscribe option. If there are just a few comments then it does not get annoying.

> 6. In notification list, mentions should be listed before new reply notifications because mentions are more important/relevant.

May be. I like the chronological order but I think there should be a way to reorder the list. Showing mentions first makes sense, though.

> > Next comment after mine may even be a reply to my comment (not everyone quotes or mention).
> No if 1. is implemented.

Sadly that's not always the case. Specially new users tend to comment either about the first comment or the last one. Without clicking on "reply", mentioning or quoting. They fill the comment box.

I think there should be a way to let the user configure whether they would like to auto subscribe or not.

> I'd like to make some PRs but I don't have time now. Have to make a living first. And it's time consuming to maintain both self (production) copy and contribution copy. And it seems that it's not able to choose a subset of all commits for pull request on GitHub.

I understand.

If you have a fork with your own changes then making PRs for both project versions (Spirit's one and yours) is tiresome, but only if there are conflicts in both versions for that part of the code, otherwise you can create one PR for both versions.

**Comment by cryptogun** [comment]
And GitHub [will auto-add new commits to existing pull request](https://stackoverflow.com/questions/11686435/how-to-stop-github-from-adding-new-commits-to-existing-pull-request). Sometimes the commits added are not so ideal. Maybe one branch per fix/feature can avoid this.

**Comment by nitely** [comment]
Yes, you have to create a branch. Most OSS project use git-flow unless they state otherwise.
