### ISSUE TITLE
Support for alternate file storages

### ISSUE THREAD

**Issue by alesdotio** [nitely/Spirit#158]
I was looking into using S3 for static and media storag, but then realized Spirit does not support it. I would suggest using [django-storages](https://github.com/jschneier/django-storages).

**Comment by nitely** [comment]
[I'm aware](https://github.com/nitely/Spirit/blob/ac86cef6c7b417755366366720f9f7e36f29dab7/spirit/comment/forms.py#L134). Supporting the `DEFAULT_FILE_STORAGE` the same way as `ImageField` should automatically fix this.

**Comment by alesdotio** [comment]
Right. Looks like it would be pretty straightforward. I might take a stab at it.
