### ISSUE TITLE
Remove ru_RU from source. 

### ISSUE THREAD

**Issue by timgin** [nitely/Spirit#161]
My apologies for a not fully accurate ticket [Remove ru_RU from transifex #160](https://github.com/nitely/Spirit/issues/160). In addition to it I suggest removing ru_RU locale from source for the same reason: there already is the 'ru' locale, which is pretty much enough and in good progress.

**Comment by nitely** [comment]
No worries. I sync locales before a new release, so it should get removed. I'll leave this open just in case.

**Comment by timgin** [comment]
Ok, thanks! I have also completed translating the "ru" locale, suppose it'll get into the new release.

**Comment by nitely** [comment]
Done here: https://github.com/nitely/Spirit/commit/3cb1a31f5c4fc10648eb2759a2ee35cc20f62a5f
Locales were updated here: https://github.com/nitely/Spirit/commit/0550f61cdea4858f30c9aaff77656007d9f9e670

closing
