### ISSUE TITLE
S3 Storage and Custom Theme/Styling

### ISSUE THREAD

**Issue by liberaltech** [nitely/Spirit#164]
I haven't been able to add AWS S3 storage. I tried using django-s3-storage and django-storages.
I get a server error.

Also, I don't exactly understand how to make changes to the styling or themes.

Every time I make some changes they don't show up when I run
python manage.py runserver

I have tried this using both Spirit and spirit-heroku versions but no change.
Am I missing something?

**Comment by nitely** [comment]
> I haven't been able to add AWS S3 storage. I tried using django-s3-storage and django-storages. I get a server error.

To storage what? static files should work just fine. Uploaded images should work as of v0.5.dev (unreleased master branch). See #158

> Also, I don't exactly understand how to make changes to the styling or themes.

Make changes to .scss (Sass) files, then compile them. Instructions are in the [/stylesheets/src](https://github.com/nitely/Spirit/tree/245bdb7eb7c16a91c9d57d1674c2db0da464fc96/spirit/core/static/spirit/stylesheets/src) folder.

To override the static files (i.e `styles.all.min.css`), err, I don't remember from the top of my head. Google it.

**Comment by liberaltech** [comment]
The storage would be for the uploads every user would be making. Again, I need to use S3 because of Heroku.

Ah, ok that makes sense for the styling.

**Comment by nitely** [comment]
Then you should either use the master branch or wait for v0.5 to be released. You can pip it `$ pip install git+https://github.com/nitely/Spirit.git` (or just clone it).
