### ISSUE TITLE
when to release v0.5.0

### ISSUE THREAD

**Issue by dhcn** [nitely/Spirit#166]
as title

**Comment by nitely** [comment]
:no_mouth: Soon? as soon as possible? whenever is ready? I dunno, there are a few thing to sort out first.

Either way you can just pip the master branch:

```
$ pip install git+https://github.com/nitely/Spirit.git@fc2ffc6ef7155398952edb60168a8a6d272cf979
```

The `@fc2ffc6ef7...` part is the last commit right now.

**Comment by nitely** [comment]
Done. Closing.
