### ISSUE TITLE
Image compression support. And remove image after link in comments was deleted.

### ISSUE THREAD

**Issue by cryptogun** [nitely/Spirit#170]
- I've implemented image compression just now:
```python
# comment/forms.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from PIL import Image as PImage
try:
    from StringIO import StringIO
except ImportError:
    # python3
    from io import BytesIO as StringIO


    def save(self):
        # todo: use DEFAULT_FILE_STORAGE and MEDIA_URL

        file = self.cleaned_data['image']

        if file.size > 1 * 1024 * 1024: # 1MB
            img = PImage.open(file)
            if img.mode != 'RGB':
                img = img.convert('RGB')
            new_img = StringIO()
            img.save(new_img, format='JPEG', quality=70)
            new_img.seek(0)
            if hasattr(new_img, 'len'):
                size = new_img.len
            else:
                size = new_img.tell()
            file = InMemoryUploadedFile(
                new_img,
                'ImageField',
                "%s.jpg"%file.name.split('.')[0],
                'image/jpeg',
                size,
                None,
            )
            file.image = img
```
Because:
1. Some VPS storage and bandwidth are expensive.
2. And larger images could take more time to load.
3. Data can be append after or encrypted into an image. What if an image of 1GB size uploaded.
- Delete image from storage after link(text) in comments was deleted, for saving disk space.
This may be implemented via ImageField in models.py or walking through all comments.
The bad thing is image links on comment history page will be broken.
- Use [django-avatar  ](https://github.com/grantmcconnaughey/django-avatar) for avatars.
It supports uploading avatar( and gravatar by default).
I've done that. But I don't have time now.
I also implemented [django-avatar compression](https://github.com/grantmcconnaughey/django-avatar/issues/146).
- Add ~~`width: 100%`~~ `max-width: 100%` to `.comment-text img`, otherwise image parts outside container will be hidden.

**Comment by nitely** [comment]
I'm actually trying to remove any image manipulation (ie: the name/hash generator). Something like this may be useful but as an optional *background/async task* (ie: a Celery delayed task).

> Data can be append after or encrypted into an image

Django checks whether the image's content is valid or not.

> What if an image of 1GB size uploaded.

I don't think you should allow such sizes. Nginx and Apache have an upload size limit which by default is just a couple MB (2MB-5MB I think).

**Comment by cryptogun** [comment]
> remove any image manipulation
Good idea. User won't wait for too long then. Compress can benefit from it. But we should provide the real image link before user posts. So I don't think name generator can be moved out.
> compared to
I've no idea, planning to buy a VPS...

**Comment by nitely** [comment]
Closing as won't fix.
