### ISSUE TITLE
Custom user's do not get along with user.admin.forms.UserForm

### ISSUE THREAD

**Issue by OdifYltsaeb** [nitely/Spirit#172]
And it's because line 17 there describes the fields for the form. In my company (https://thorgate.eu/) we use user without username. We use email instead of username. 

So i propse a fix, which i could implement myself (since i want to test spirit little more, in hopes we can use it in one of our new projects) where the user fields that are required @ signup come from settings. 

I understand that for forum, having a username makes sense. But you might consider having some other method on user for returning user name - full_name or anything... 

in additon to that, you also have first_name & last_name as required fields for user.forms.UserForm. That in my opinion, should also be customisable, because it really does not work well with custom user models.

I guess, this applies to all the forms that have something todo with user.

**Comment by OdifYltsaeb** [comment]
So if we could figure out a way to do this, then this would not be a mess? Perhaps a better way to do this is to make all the necessry forms interchangeable or configurable? That would perhaps make managing this easyer? Then you could have rest of the code still use User.username for mentions, but the forms would work for all the views that need them.

**Comment by OdifYltsaeb** [comment]
I feel like the whole root of the problem is that you meant to have your project used as a stand-alone solution, but we are trying to use this as part of a bigger site. What do you think? 

I'm trying to figure out what would be the best way to modify your existing project to fit our needs without compromising your goals. Perhaps there is a common ground yet?

**Comment by nitely** [comment]
> I feel like the whole root of the problem is that you meant to have your project used as a stand-alone solution, but we are trying to use this as part of a bigger site. What do you think?

That's not completely right, though. It's something I usually say when someone tries to use Spirit in other way than a forum or in other way that it was intended to be used.

There are hard requirements. `usernames` is one of them. You need a way to identified users that's actually useful to users. I can't ask users to mention by typing a user_ID, who remembers that?

> Perhaps a better way to do this is to make all the necessry forms interchangeable or configurable? That would perhaps make managing this easyer? Then you could have rest of the code still use User.username for mentions, but the forms would work for all the views that need them.

But you need the actual field in your user's model/table. There are database queries that use it. There is a bunch of features that require users to be identified in a user-friendly way. Making forms swappable is not enough. For example, to create a private conversation users must invite other users and the current way of doing that is by entering their `usernames`.

Supporting optional `usernames` would really complicate current and future development.

**Comment by OdifYltsaeb** [comment]
Allright. I'll think about this for a while. But i guess i will close this issue for now and if i have some kind of complete solution, that does not complicate any further development, then i'll create new issue for it.
