### ISSUE TITLE
can't run example application

### ISSUE THREAD

**Issue by laolai** [nitely/Spirit#175]
I use Python 3.5.3 , try to run the command "pip install . " and I get these errors:

Collecting unicode-slugify==0.1.3 (from django-spirit==0.5.0.dev0)
  Using cached unicode-slugify-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-y1vmyhid/unicode-slugify/setup.py", line 7, in <module>
        long_description=open('README.md').read(),
      File "/root/Envs/spirit/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 361: ordinal not in range(128)

**Comment by srignanvijay** [comment]
Assuming you are using ubuntu try with docker Add these commands to the Dockerfile to work around this 
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en


if you are not using docker 
root# locale-gen en_US.UTF-8
root# export LANG en_US.UTF-8
root# export LANGUAGE en_US:en
then try a reboot might work

**Comment by nitely** [comment]
This is an issue in `unicode-slugify` and they are aware of it. It does not seem they are going to fix it any time soon, tough. You may remove that dependency from the requirements file (Spirit will still work) or follow @srignanvijay workaround.

**Comment by nitely** [comment]
I have made a temporary fix for this. I'll merge the PR in a few.

**Comment by laolai** [comment]
thanks!
