### ISSUE TITLE
no such table: djconfig_config

### ISSUE THREAD

**Issue by skilfulcoding** [nitely/Spirit#177]
```
OperationalError at /

no such table: djconfig_config
```

Hello I am using Spirit for the first time. To start I am installing it as a standalone project. 
I get the above error when I run the app, from django debugger. 

I tried python manage.py migrate again but it said no migrations

The settings.py was in the example project didn't have database settings, so I added these: - 

> BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
> 
> DATABASES = {
>     'default': {
>         'ENGINE': 'django.db.backends.sqlite3',
>         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
>     }
> }

Any idea how I can fix this error?

**Comment by nitely** [comment]
Are you trying the `example` project?

**Comment by skilfulcoding** [comment]
Thanks for checking, yes I followed the install steps, all except the last 

python manage.py runserver

As I'm using uwsgi

**Comment by nitely** [comment]
Can you paste your settings content here?
