### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by trdwll** [nitely/Spirit#180]
- Is this still in active development?
- How frequent do you push updates that would be recommended for production environments? 
- What's the security like? What hashing algorithm is used for passwords etc?

Sorry if these have already been answered. I'm tired and too lazy to look around currently.

**Comment by nitely** [comment]
* yes
* It varies. Usually, you should update on every release.
* Check the django framework.

If you are too lazy to open and read the changelog better use one of the
many forum alternatives instead of this one ;) . You'll get better support.

**Comment by trdwll** [comment]
Thanks for your response. I was tired last night, I had just got off work and was going to bed. Sorry about that.
