### ISSUE TITLE
Missing features when integrating Spirit

### ISSUE THREAD

**Issue by Iamsoto** [nitely/Spirit#185]
Hello There! 

I'm currently working on a Django project that integrates your spirit forums into our website. 

I am able to install spirit alongside our Django project and run it successfully. It appears the spirit UserProfile links well with our own user models. However, I can't help but notice we are missing a few features the spirit forum is supposed to provide, such as categories (we only get the option uncategorized), also notifications and private messaging doesn't seem to be present. I can't seem to figure out why. Do you perhaps have insight as to why this might be? 

Thank you.

Here are the images of the forum's home and the Create Topic page

![hello world](https://user-images.githubusercontent.com/13967954/27521583-8e03de60-59d3-11e7-83dc-b73e8b0103a0.png)

![hello world create topic](https://user-images.githubusercontent.com/13967954/27521653-49b348c6-59d4-11e7-80b1-62fdb9343c67.png)

**Comment by nitely** [comment]
> I can't help but notice we are missing a few features the spirit forum is supposed to provide, such as categories (we only get the option uncategorized)

Only the `Uncategorized` category is create by default. To create a new category go into `admin->categories->create category` section. You need *superuser* rights in order to access te admin section.

> also notifications and private messaging doesn't seem to be present. I can't seem to figure out why.

Looking at the screenshots it seems you have removed part of the forum header which contains the user menu.

**Comment by Iamsoto** [comment]
You're right, it was the _header.html 
Thank you

**Comment by nitely** [comment]
Awesome. You are welcome :smile:
