### ISSUE TITLE
Upload documents

### ISSUE THREAD

**Issue by jgmejia** [nitely/Spirit#188]
I would like to know if there is an option to upload documents, in a similar way as can be done with images.
I want users to upload some PDFs to share with other users (viewing the document through the browser is not required).

Thanks in advance for your help.

**Comment by rkenmi** [comment]
Is anyone working on this? I would like to volunteer.

**Comment by nitely** [comment]
AFAIK, no one is working on this. Implementation should be pretty similar to the images one (except there is no way to validate files).

**Comment by nitely** [comment]
Fixed in #194
