### ISSUE TITLE
Fix misspelling of choose (from chose).

### ISSUE THREAD

**Issue by romeojulietthotel** [nitely/Spirit#191]
https://github.com/nitely/Spirit/blob/4b53631490364c1bafbbca7ae1d803cdab3adfff/spirit/topic/forms.py#L36

https://github.com/nitely/Spirit/pull/190

**Comment by nitely** [comment]
Hey

The way of fixing this is just translating that `messageID` into the right sentence (*Choose a category*). So, to do that just create a [transifex] account and join the english translation team (I'll approve the request ASAP)

[transifex]: https://www.transifex.com/projects/p/spirit/

**Comment by nitely** [comment]
Well, it seems transifex does not allow to translate the source language (English). I'll try and change the .po file and update the transifex source.

**Comment by romeojulietthotel** [comment]
Knowing next to nothing about transifex or translation I think I'm useless in this area.  I didn't know about this translation workflow.  Seems like a considerable amount of extra work. But there's probably less work to do it this way in the long run.

**Comment by nitely** [comment]
Transifex is just a UI for translating .po files. So people can translate
there in real time at the same time and there is no need for making PRs or
knowing anything about git. Easier for the non-techie

**Comment by romeojulietthotel** [comment]
I updated the .po files and pushed them now.

Thank you for explaining transifex (I thought it was a disease). I read a little more bout translation in django and they seem to have it well covered. But I don't really need it yet (maybe one day).  I got curious on how to build the .mo files and it seems like django-admin is what's used to do that. But django-admin only works in a project so how to run it in Spirit git environment?  I probably don't need to but now I am interested to know. Is this a Django thing too?

**Comment by nitely** [comment]
Great! I'll update the transifex files on the weekend!

> But django-admin only works in a project so how to run it in Spirit git environment?

What I do is create a `manage.py` file within Spirit git env root and then add the example project to its `DJANGO_SETTINGS_MODULE` env var, then I can run the usual Django commands `$ manage.py ...` or `$ django-admin ...`. Both ways of invoking a django command should work.

To create po files and compile them into mo files I run `$ manage.py spiritmakelocales` [0] which just runs `$ django-admin makemessages && django-admin makemessages compilemessages` for every Spirit app.

Django translation system is just a layer over [Python's gettext module](https://docs.python.org/3/library/gettext.html)

[0] https://github.com/nitely/Spirit/blob/master/spirit/core/management/commands/spiritmakelocales.py#L25
