### ISSUE TITLE
Spirit integration into mezzanine- help!!

### ISSUE THREAD

**Issue by Robinsondev** [nitely/Spirit#192]
Hello Nitely! To start your package is AMAZING. I fall in love with it wright after i tested the example on the repo.
My problem is that It has been about 2 weeks that I have been trying to integrate Spirit in to my mezzanine project. It is a big pain because I tried a couple things around the internet but was unlucky. This is what i have tried

http://www.adamwester.me/blog/integrate-spirit-forum/ and i got this error "django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.", I checked the  __init__.py of spirit, and commented the function out but nothing.

Then i tried this https://community.spirit-project.com/topic/318/tutorial-for-not-advanced-django-users/ I was also unsuccessful

I then went here: https://github.com/nitely/Spirit/issues/25 but the post is 3 years old and does not give much information.

Gus please save me if there is something that had previously worked for you, please let me know

**Comment by nitely** [comment]
What django version did you try this on?

**Comment by Robinsondev** [comment]
Thank you for the response. I am using Django 1.10

**Comment by nitely** [comment]
ok, it shoud work then.

> http://www.adamwester.me/blog/integrate-spirit-forum/ and i got this error 

Don't follow that guide.

> I then went here: #25 but the post is 3 years old and does not give much information.

Yeah, that's old. Spirit no longer implements a custom user model, so that issue should be completely irrelevant.

Do the following:

Go to [spirit.settings](https://raw.githubusercontent.com/nitely/Spirit/v0.4.x/spirit/settings.py) and copy/paste each setting into your project settings. Merge the duplicated settings (such as `installed_apps` and `middlewares`).

Add `url(r'^discuss/', include(spirit.urls)),` to urls.py (remember to import `spirit.urls` as well)

Then run the following commands:

```
$ pip install django-spirit
$ python manage.py spiritinstall
```

> Last command runs migrate and collectstatics commands

PS: Starting from Spirit 0.5 all of this will no longer be valid as there will a better way of installing Spirit. See #193

**Comment by Robinsondev** [comment]
Thanks, I am gonna do that right now!

**Comment by nitely** [comment]
Ok, let me know how it goes. As a last resource I'll just try mezzanine myself :smile_cat: but I hope not.

**Comment by Robinsondev** [comment]
The installation works! Thanks a lot! 
Now the problem is that Mezzanine has its user model and spirit also has its own. So when i click on login on Spirit's side, I get 


Request Method: | GET
-- | --
http://127.0.0.1:8000/discuss/user/login/?next=/discuss/category/2/uncategorized/
mezzanine.pages.views.page

I must say that initailly I tried to install without this:


AUTHENTICATION_BACKENDS = [
    'spirit.user.auth.backends.UsernameAuthBackend',
    'spirit.user.auth.backends.EmailAuthBackend',
]
then login did not work. And after I added it it still did not work. So How to make them work together?

**Comment by Robinsondev** [comment]
I am even thinking about using django-allauth to simply get rid of mezzanine authentication and use google and facebook

**Comment by nitely** [comment]
Oh right. These two settings lines are the problem:

```python
LOGIN_URL = 'spirit:user:auth:login'
LOGIN_REDIRECT_URL = 'spirit:user:update'
```

You can revert them to what you previously had. If those lines did not exists then just remove them. That way you would use the mezzanine login only. However you now probably have two ways to register users, no? (mezzanine and spirit registrations). I'm not sure if that would be a problem. If it is you can override the spirit urls and redirect them to mezzanine registration.

> Now the problem is that Mezzanine has its user model and spirit also has its own

Just to be clear, Spirit *does not has a user model*, it has a model that makes a `OneToOne` relationship to whatever user model you have (django or a custom one), but should not be a problem whatsoever.

**Comment by nitely** [comment]
Btw if you want to use spirit login instead of mezzanine then add those two lines :smile_cat:

**Comment by Robinsondev** [comment]
Ok I added the 2 lines and now it work well. No issue! Thanks A LOT! You saved me. 
Can you please give me tips on how to style the forum a little differently? Like change the name at the top and put some background color ? 

Thanks @nitely :smile_cat:

**Comment by nitely** [comment]
> Ok I added the 2 lines and now it work well. No issue! Thanks A LOT! You saved me.

Great! you are welcome :smile: 

The name can be changed from the control-panel `/st/admin/` . There's no easy way to change CSS properties. You have to override the `templates/spirit/_base.html` template. Create that structure witin the root of your project. Add `spirit/core/templates/spirit/_base.html` content into it and modify as needed (i.e: add style tags and override the background). I should work on an easier way :sweat:

**Comment by Robinsondev** [comment]
Thanks. I am gonna create a nice template to overwrite some things and I will let you know.

> P.S:

 For those who did not get "/st/admin", make sure you put the name of the url that you chose before "st/admin". In my case It was : discuss/st/admin. I thought it could be helpfull

> 

Thanks. Please don't close the topic yet. I m gonna be back asap everything works and I will explain all I did so that other people can benefit. Thanks again. You are a life saver

**Comment by Robinsondev** [comment]
So for the default template, I guess I will have to do 
python manage.py collecttemplate
so that i can have the default structure of the base template right?

**Comment by nitely** [comment]
That's not necessary. I tried it a while ago. Just create the structure for
that single file.

**Comment by nitely** [comment]
If that does not override it, then you may have to add some setting. I'll
check.

**Comment by nitely** [comment]
According to [#44](https://github.com/nitely/Spirit/issues/44#issuecomment-98526295), gotta add:

```python
# settings.py

TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'templates')]
```

**Comment by nitely** [comment]
Oh, it seems that setting was remove from django. You have to add `DIR` to `TEMPLATES` settings now. Like this:

```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  # This!
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

**Comment by Robinsondev** [comment]
Hi @nitely, thanks for the responses. I was gonna get back to you earlier but here is what happened:

I created my template and was ready to run the app and test when I got into this error:
page not found 404 

Request URL: | http://127.0.0.1:8000/discuss/
-- | --
mezzanine.pages.views.page

I checked my setting over and over (for a couple hours and tested a couple things)

in my url.py provided by Mezzanine, I have this:

   #mezzanine
   url("^", include("mezzanine.urls")),
    #spirit
    url(r'^discuss/$', include(spirit.urls)),

Only mezzanine links work. A quick thing that I tried was to add a prefix to Mezzanine. In my case I added "mez", like this    url("^mez/", include("mezzanine.urls")), but then the links that came in with mezzanine when I installed it where not working anymore except for the home link. 


So at this point I have looked around, trying to find the way to make both work on the url side but I can't get it.   I also checked this  http://mezzanine.jupo.org/docs/content-architecture.html#third-party-app-integration but I have no clue how that will match with Spirit.

Do you know if there is something I maybe missing?

Do you know if there is something I maybe missing?

**Comment by nitely** [comment]
Try switching the url patterns. Like this:

```python
#spirit
url(r'^discuss/', include(spirit.urls)),  # removed end of string ($)
#mezzanine
url(r"^", include("mezzanine.urls")),  # added raw string prefix (r"")
```

My guess is mezzenine has a sort of match all urls, so spirit doesn't get a change to match its URLs. I also fixed a couple mistakes in both patterns.

**Comment by Robinsondev** [comment]
Thanks for the fast response, Now the error that I get is 

AttributeError at /

'tuple' object has no attribute 'regex' :)

**Comment by nitely** [comment]
Can you paste the whole urls.py here?

**Comment by Robinsondev** [comment]
I think It is working better. Let me test with the template please. Thanks

**Comment by Robinsondev** [comment]
It works well now. Still testing with template. Thanks a lot. I am still gonna share my urls.py with other people so that they can benefit 

from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings
import spirit.urls

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    # url("^", include("mezzanine.urls")),
    #
    #
    # #spirit
    # url(r'^discuss/', include(spirit.urls)),

    #spirit
url(r'^discuss/', include(spirit.urls)),  # removed end of string ($)
#mezzanine
url(r"^", include("mezzanine.urls")),  # added raw string prefix (r"")


    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

**Comment by nitely** [comment]
Great! Let me know if you get blocked again :smile_cat:

**Comment by Robinsondev** [comment]
Thanks! Here is what I did with templates, I went to https://github.com/nitely/Spirit/tree/master/spirit/core/templates/spirit

then in created  'spirit/core/templates/spirit/_base.html'  in the root directory. After that I created  this :   


{% load spirit_tags i18n %}
{% load static from staticfiles %}

 {% block head-extra %}
<a class="simple" href="#">polo</a>
 {% endblock %}

I could not get it done, so was trying to add and additional menu item to the navbar. I failed. :) 

am i missing anything? 
THanks

**Comment by nitely** [comment]
You have to create `templates/spirit/_base.html` (not `spirit/core/templates/spirit/_base.html`) at the root. That I'm sure of. Then add the `DIR` key within `TEMPLATES` as I suggested [0]

[0] https://github.com/nitely/Spirit/issues/192#issuecomment-328485076

**Comment by nitely** [comment]
Oh, don't put anything within a `{% block %}` as that will replaced by whatever a child template puts in there (if they do). Here are the docs [0]

[0] https://docs.djangoproject.com/en/1.11/ref/templates/language/#template-inheritance

**Comment by nitely** [comment]
> I could not get it done, so was trying to add and additional menu item to the navbar. I failed. :)

To add an item you gotta override the `_header.html`.

**Comment by Robinsondev** [comment]
Oh Ok! Thanks

So I did this

```
<header>
  <a class="simple" href="#">polo</a>
</header>

So I got this!
![screen1](https://user-images.githubusercontent.com/31787218/30315649-4346888e-977f-11e7-9132-1d5bd8d0cd5d.png)

```

I am gonna ovveride the _header tag and try a couple other things

THanks

**Comment by nitely** [comment]
Yeah, that's coz you didn't included the whole `_base.html` content. The base is used by pretty much every section of the site. It's the only place to add extra CSS for now.

> I am gonna ovveride the _header tag and try a couple other things

Don't forget to include the whole _header file content and then modify as needed.

**Comment by Robinsondev** [comment]
Hello, I trying to write a detailed documentation about how i made everything work. So please be patient. :100:
