### ISSUE TITLE
Support for Django 2.0

### ISSUE THREAD

**Issue by nitely** [nitely/Spirit#199]
Leaving this advice from Django 1.11 release notes, so I remember to actually follow it:

> Following the release of Django 2.0, we suggest that third-party app authors drop support for all versions of Django prior to 1.11. At that time, you should be able run your package’s tests using python -Wd so that deprecation warnings do appear. After making the deprecation warning fixes, your app should be compatible with Django 2.0.

**Comment by olymk2** [comment]
Are we likely to see support for django 2 any time soon ?

**Comment by nitely** [comment]
Probably not until the next LTS comes out

**Comment by olymk2** [comment]
is there an eta on that ?

**Comment by nitely** [comment]
Next LTS is on April 2019, AFAIK. There's probably very little to be done. Django 2.0 is pretty much Django 1.11, and Django 2.1 should be pretty much the same as well.

**Comment by nitely** [comment]
Now that I think about it, there is a bunch of deprecation warnings (`python -Wd`) that should be fixed, but should be easy to do.

**Comment by nitely** [comment]
So, Django 1.8 has reach EOL on April. So, I'll start working on supporting django +2.0 this weekend.

**Comment by nitely** [comment]
Done

**Comment by olymk2** [comment]
Awesome upgraded on stage and seems to be working with no issues for me :)

**Comment by nitely** [comment]
@olymk2 Great! let me know if there are any issues.
