### ISSUE TITLE
file upload 

### ISSUE THREAD

**Issue by sasimi19** [nitely/Spirit#203]
Hi!! 
Thanks for your help until now ~ 
I have an another issue.
when i upload image files, it's ok
but uploading pdf files, it makes a below error
{"error":{"file":["The file could not be validated"]}}

Can I upload other kinds of files like excel, powerpoint and so on??

**Comment by nitely** [comment]
You are on Windows, right? the file validator does not work on Windows ATM. I'll work on that. There should be an error logged in the console (or logs).

> Can I upload other kinds of files like excel, powerpoint and so on??

Yes. There is a setting for allowed file formats [0]

[0] spirit.readthedocs.io/en/latest/settings.html

**Comment by sasimi19** [comment]
Yes I use Windows. 

error logs are below
it's from apache logs

[Wed Oct 25 10:17:02.794759 2017] [wsgi:error] [pid 2840:tid 1684] [client ::1:63515] c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\django_spirit-0.5.0.dev0-py3.5.egg\\spirit\\core\\utils\\ratelimit\\ratelimit.py:77: RemovedInNextVersionWarning: settings.ST_RATELIMIT_CACHE cache's TIMEOUT must be None (never expire) and it may be other than the default cache. To skip this check, for example when using a third-party backend with no TIMEOUT option, set settings.ST_RATELIMIT_SKIP_TIMEOUT_CHECK to True. This will raise an exception in next version.\r, referer: http://localhost:8001/bbs/topic/active/
[Wed Oct 25 10:17:02.832761 2017] [wsgi:error] [pid 2840:tid 1684] [client ::1:63515]   validate_cache_config()\r, referer: http://localhost:8001/bbs/topic/active/
[Wed Oct 25 10:35:07.162781 2017] [wsgi:error] [pid 2840:tid 1684] [client ::1:53380] c:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\pkg_resources\\__init__.py:1268: UserWarning: C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming\\Python-Eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).\r, referer: http://localhost:8001/bbs/topic/publish/5/
[Wed Oct 25 10:35:07.222784 2017] [wsgi:error] [pid 2840:tid 1684] [client ::1:53380]   warnings.warn(msg, UserWarning)\r, referer: http://localhost:8001/bbs/topic/publish/5/

**Comment by nitely** [comment]
I don't see anything related to the validator. Python errors are likely not being logged. I think you have to add `'file'` handler to `LOGGING` setting. Like this:

```python
'loggers': {
        '': {
            'handlers': ['console', 'mail_admins', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'mail_admins', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    }
}
```

Then restart the server and try uploading a pdf file. The error should be logged into `...../myproject/django.log`. However, I know what the error is. The path to the magic file must be supplied to the magic validator on Windows [0], but that's not currently possible.

[0] https://github.com/ahupp/python-magic#dependencies

**Comment by sasimi19** [comment]
i will try and let you thanks

**Comment by sasimi19** [comment]
the error is below. please check this. 
thanks in advance
-------------------------------------------------------------------------------
[25/Oct/2017 17:36:58] "POST /user/register/ HTTP/1.1" 302 0
[25/Oct/2017 17:36:58] "GET /user/login/ HTTP/1.1" 200 2889
[25/Oct/2017 17:40:41] "POST /user/login/ HTTP/1.1" 302 0
[25/Oct/2017 17:40:41] "GET /user/ HTTP/1.1" 200 32847
[25/Oct/2017 17:40:43] "POST /user/ HTTP/1.1" 302 0
[25/Oct/2017 17:40:43] "GET /user/ HTTP/1.1" 200 33368
[25/Oct/2017 17:40:47] "GET / HTTP/1.1" 200 4752
[25/Oct/2017 17:40:48] "GET /topic/publish/ HTTP/1.1" 200 8028
b'could not find any magic files!'
Traceback (most recent call last):
  File "C:\Users\1111\AppData\Local\Programs\Python\Python35-32\lib\site-package
s\django_spirit-0.5.0.dev0-py3.5.egg\spirit\comment\forms.py", line 189, in clea
n_file
    file_mime = magic.from_buffer(file.read(), mime=True)
  File "C:\Users\1111\AppData\Local\Programs\Python\Python35-32\lib\site-package
s\python_magic-0.4.13-py3.5.egg\magic.py", line 142, in from_buffer
    m = _get_magic_type(mime)
  File "C:\Users\1111\AppData\Local\Programs\Python\Python35-32\lib\site-package
s\python_magic-0.4.13-py3.5.egg\magic.py", line 118, in _get_magic_type
    i = _instances[mime] = Magic(mime=mime)
  File "C:\Users\1111\AppData\Local\Programs\Python\Python35-32\lib\site-package
s\python_magic-0.4.13-py3.5.egg\magic.py", line 67, in __init__
    magic_load(self.cookie, magic_file)
  File "C:\Users\1111\AppData\Local\Programs\Python\Python35-32\lib\site-package
s\python_magic-0.4.13-py3.5.egg\magic.py", line 259, in magic_load
    return _magic_load(cookie, coerce_filename(filename))
  File "C:\Users\1111\AppData\Local\Programs\Python\Python35-32\lib\site-package
s\python_magic-0.4.13-py3.5.egg\magic.py", line 190, in errorcheck_negative_one
    raise MagicException(err)
magic.MagicException: b'could not find any magic files!'
[25/Oct/2017 17:43:27] "POST /comment/upload/file/ HTTP/1.1" 200 56

**Comment by nitely** [comment]
Yes, that's it. I'll fix it ASAP.

**Comment by sasimi19** [comment]
hi ! 
I solved the magic problem by specifying magic path to in spirit.comment.forms.py
by the way the validate error was gone 
but [error: error Internal Server Error]() happened
the detail is below
now i am watching editor_file_upload.no-min.js
but I don't know where the error happen

Performing system checks...
System check identified no issues (0 silenced).
October 31, 2017 - 22:04:33
Django version 1.10, using settings 'spirit_171016.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /comment/upload/file/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django_spirit-0.5.0.dev0-py3.5.egg\spirit\comment\forms.py", line 185
, in clean_file
    file_mime = magic.from_file(file.temporary_file_path(), mime=True)
TypeError: from_file() got an unexpected keyword argument 'mime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django_spirit-0.5.0.dev0-py3.5.egg\spirit\comment\views.py", line 151
, in file_upload_ajax
    if form.is_valid():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\forms\forms.py", line 169, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\forms\forms.py", line 161, in errors
    self.full_clean()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\forms\forms.py", line 370, in full_clean
    self._clean_fields()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django\forms\forms.py", line 391, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\django_spirit-0.5.0.dev0-py3.5.egg\spirit\comment\forms.py", line 188
, in clean_file
    except magic.MagicException as e:
AttributeError: 'Magic' object has no attribute 'MagicException'
"POST /comment/upload/file/ HTTP/1.1" 500 22665

**Comment by sasimi19** [comment]
hi ~ I solved the problem.
for my case, I inserted in the forms.py of the "comments" folder
magic=magic.Magic(magic_file='C:\\Program Files\\GnuWin32\\share\\misc\\magic',mime=True)
and I removed mime=True in 1), 2)
Thanks for your help~ 

1) file_mime = magic.from_file(file.temporary_file_path())#, mime=True)
2) file_mime = magic.from_buffer(file.read())#, mime=True)

**Comment by sasimi19** [comment]
I have an another question.
I tried to upload various kinds of file formats "xlsx, pptx, psd, ai and so on"
but for some file formats, it returned "Unsupported file mime type CDF V2 Document, corrupt: Cannot read summary info"
I followed the settings in the "https://spirit.readthedocs.io/en/latest/settings.html"

how can I add other file formats?
Thanks in advance

**Comment by nitely** [comment]
That's either a libmagic problem, a problem with the program you are using to generate the file or with the file itself (maybe it's corrupted?).

That said, I don't think libmagic supports every format out there. Also, it's not always possible to guess the mime type, since some programs (usually alternatives to the original program) will create the file without the info to guess it.

AFAIK there is nothing better than libmagic. I don't know where to report libmagic bugs, but you should report it there.

**Comment by nitely** [comment]
There is an easier way to solve this now: `pip install python-magic-bin` that'll install python-magic and the required binaries, also no need to pass a path.

`python-magic` is now an extra dependency of Spirit, meaning it's not installed by default. It requires running `pip install django-spirit[files]` (or `pip install .[files]` for now, since Spirit v05 is not released yet) and that will install the binaries as well 😃 .

Closing.
