### ISSUE TITLE
Spirit 0.5 integration into mezzanine- help!!

### ISSUE THREAD

**Issue by nabeelakhtar9** [nitely/Spirit#222]
Hello Nitely! I really like your package. Your forum is perfect according to my need.

My problem is that I have been trying to integrate Spirit in to my mezzanine project.  I tried a couple things around the internet but was unlucky. 

I tried #192  but i found that Starting from Spirit 0.5 all of this will no longer be valid.

Kindly guide me how can i integrate spirit 0.5 and plus into mezzanine. Thanks

**Comment by nitely** [comment]
Hey,

This seems to be a common request so I'l try and add a guide to the docs this weekend. But for now you can try this:

First of, do all of this on a local machine first, not in the production site.

Install Spirit and make sure it works:

```
# git is required since Spirit v0.5 is not out yet
pip install git+git://github.com/nitely/Spirit.git
spirit startproject mysite
cd mysite
python manage.py spiritinstall
python manage.py createsuperuser
python manage.py runserver
```

All of this is required so you can copy Spirit settings into your mezzanine project. This should have generated `/mysite/settings/base.py`. You've to [manually] merge that file's content with your current site's settings.py.

Pip install Spirit v0.5 by running `pip `

Include Spirit URLs into the mezzanine project y adding `import spirit.urls` and `url(r'^forum/', include(spirit.urls)),` into `urls.py`

Then run:

```
# spiritinstall runs migrate and collectstatics
python manage.py spiritinstall
python manage.py createsuperuser
python manage.py runserver
```

That should be it.
