### ISSUE TITLE
relation "djconfig_config" does not exist

### ISSUE THREAD

**Issue by dimworm** [nitely/Spirit#225]
ProgrammingError at /
relation "djconfig_config" does not exist
LINE 1: ...fig_config"."key", "djconfig_config"."value" FROM "djconfig_...
                                                             ^
Request Method:	GET
Request URL:	http://xxxx.io/
Django Version:	1.11.8
Exception Type:	ProgrammingError
Exception Value:	
relation "djconfig_config" does not exist
LINE 1: ...fig_config"."key", "djconfig_config"."value" FROM "djconfig_...
                                                             ^
Exception Location:	/home/particle/www/myenv/lib/python3.5/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/home/particle/www/myenv/bin/python3
Python Version:	3.5.2
Python Path:	
['/home/particle/jblog',
 '/home/particle/www/myenv/bin',
 '/home/particle/www/myenv/lib/python35.zip',
 '/home/particle/www/myenv/lib/python3.5',
 '/home/particle/www/myenv/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/particle/www/myenv/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/particle/www/myenv/lib/python3.5/site-packages']
Server time:	Sat, 23 Dec 2017 11:15:02 +0000

I've tried setup different databases. But the problem remains. How can I fix it? Thank you.

**Comment by nitely** [comment]
Lets start fresh. Try this and let me know if it works:

```
# piping the repo is required since Spirit v0.5 is not out yet
pip install --upgrade https://github.com/nitely/Spirit/archive/master.tar.gz
spirit startproject mysite
cd mysite
python manage.py spiritinstall
python manage.py createsuperuser
python manage.py runserver
```

**Comment by dimworm** [comment]
I'm trying to deploy to production, but I forget to change "settings.dev" to prod in manage.py file.
