### ISSUE TITLE
Run Spirit with different languages

### ISSUE THREAD

**Issue by t4r7s** [nitely/Spirit#226]
I want to run Spirit with 'ru' - language. But I can't make it. 
I use: `Django version 1.11.8, using settings 'mysite.settings.dev'`
I added to settings/dev.py code: 
```

# These are all the languages Spirit provides.
# https://www.transifex.com/projects/p/spirit/
gettext_noop = lambda s: s
LANGUAGES = [
    ('de', gettext_noop('German')),
    ('en', gettext_noop('English')),
    ('es', gettext_noop('Spanish')),
    ('fr', gettext_noop('French')),
    ('hu', gettext_noop('Hungarian')),
    ('pl', gettext_noop('Polish')),
    ('pl-pl', gettext_noop('Poland Polish')),
    ('ru', gettext_noop('Russian')),
    ('sv', gettext_noop('Swedish')),
    ('tr', gettext_noop('Turkish')),
    ('zh-hans', gettext_noop('Simplified Chinese')),
]

# Default language
LANGUAGE_CODE = 'ru'

```

Its not actually working. What I should to do next?

**Comment by nitely** [comment]
Is your OS or browser in another language? If it's then the browser must be
sending whatever lang your are seeing as the acepted lang (check the
request headers). Try removing all lenguages but ru from the list and see
if that "fixes" it.

**Comment by t4r7s** [comment]
> Is your OS or browser in another language? If it's then the browser must be
sending whatever lang your are seeing as the acepted lang (check the
request headers). Try removing all lenguages but ru from the list and see
if that "fixes" it.

I done this. But is not actually helps. It is doest matter - if I try only 'ru' or 'en' (by default). I see the same picture (only few words are Russian): http://joxi.ru/J2bg4W7s4e3e7A
It seems like language detect is working, but only few words are traslated. But I saw if transation's files - many words are complete.

**Comment by t4r7s** [comment]
```
# Default language
LANGUAGE_CODE = 'zh-hans'

```

Chineese is better - if using by default, but again few words in Russan:
http://joxi.ru/823dLBZt6QZkQA

**Comment by nitely** [comment]
Oh, translations are outdated. The ru translation is complete (at Spirit's transifex project), but I've not updated the files yet.

**Comment by t4r7s** [comment]
When will you updating files?

**Comment by nitely** [comment]
Done. Sorry about the delay!
