### ISSUE TITLE
  Can you deploy the project to the public network? 

### ISSUE THREAD

**Issue by jiangsi520** [nitely/Spirit#234]
Can only be tested locally? I tried Python manage.py runserver -h IP -p POST not functioning properly.
![image](https://user-images.githubusercontent.com/30169495/41712520-4ef33fce-757d-11e8-8db2-d319b514b211.png)

The default is yes
![1111](https://user-images.githubusercontent.com/30169495/41712504-439ea5f0-757d-11e8-9201-f6ba3906a8f6.jpg)

**Comment by nitely** [comment]
There are many ways to "deploy the project to the public network". Deploying Spirit into the cloud or some server is not different than deploying Django. So, pick a cloud or hosting service and use google to learn how to deploy.

There is a one-click deploy to heroku project, FWIW. https://github.com/nitely/spirit-heroku
