### ISSUE TITLE
Excuse me, I need to modify the upload settings. Where do I need to upload more format suffixes?

### ISSUE THREAD

**Issue by jiangsi520** [nitely/Spirit#236]
I can't upload files in other formats after I modify the settings.py and defaults.py, and the files of the screenshots can't be uploaded in any format. The mistakes are as follows:

![c8 2c k1f_se8rndmcfhr](https://user-images.githubusercontent.com/30169495/42928941-412a3a42-8b6b-11e8-8e65-2deda3b81e5f.png)

![default](https://user-images.githubusercontent.com/30169495/42929286-38f4cbd4-8b6c-11e8-96a1-4014031b6fcf.png)

**Comment by nitely** [comment]
Have you restarted the server yet? Changes to settings.py require a python
server restart to take effect (whatever that is: gunicorn, uwsgi or
runserver). Also, extensions should be case insensitive, no need for the
uppercase duplications. Btw, PNG is a security risk, read the note.

**Comment by nitely** [comment]
If restarting the server has no effect, then you may be doing these changes in the wrong place. Try adding a `print("yep, these settings are loaded")` there and check it's printed in the console.

**Comment by jiangsi520** [comment]
Well, thank you for your answer
