### ISSUE TITLE
Notification does not clear after viewing it

### ISSUE THREAD

**Issue by psukys** [nitely/Spirit#237]
For quite a long time I had a notification saying that a person commented in a specific topic. Even after going to that topic, viewing the post, then posting by myself, the notification did not clear up (remained as unread).

Recently, I found a way to workaround this by going to unread topics page and going through all of the unread topics. After that, the notification was cleared.

Website this was running from: [ubuntu.lt](https://ubuntu.lt)

**Comment by nitely** [comment]
It seems you're talking about two things. "Notification" is not the same as "unread". If you mean the "unread" mark (the red comment icon), then [I know what this is](https://github.com/nitely/Spirit/issues/136). If you mean the user "notification" bell, then I've no idea. Once you click on a notification received link, the notification status changes to "read" and the bell turns grey again. This would be the first time I heard that does not work for some reason, and without a way to reproduce it there's nothing I can do about it.

**Comment by nitely** [comment]
mmh I think the notification may not go away when the comment no longer exists (i.e on a manual removal). But in that case, when clicking the notification link, it would take you to the topic instead of to the specific comment.

**Comment by psukys** [comment]
Regarding the problem domain, I meant the "notification" bell.  The notification did not clear up after clicking the bell and click the corresponding entry that had "unread" label.

**Comment by nitely** [comment]
Ok, I can probably do something about it, like clear the notification regardless of the topic/comment being removed/moved/etc. I'll take a look later. Thanks for reporting this @psukys

**Comment by nitely** [comment]
I was able to reproduce this. This occurs when a comment is posted in a topic you are subscribed to and then moved somewhere else, then you have to find the original topic to set the notification as read. I'll fix it.
