### ISSUE TITLE
Any reason why these depenancies can not be upgraded ?

### ISSUE THREAD

**Issue by olymk2** [nitely/Spirit#238]
django-spirit 0.6.0 has requirement django-djconfig<0.6,>=0.5.1, but you'll have django-djconfig 0.7.0 which is incompatible.
django-spirit 0.6.0 has requirement Pillow==4.2.1, but you'll have pillow 5.2.0 which is incompatible.

warnings when launching my django app can we have the max versions increased ?

**Comment by nitely** [comment]
No. Just make a PR next time.
