### ISSUE TITLE
mistune <0.8.1 vulnerable to XSS

### ISSUE THREAD

**Issue by KittenHero** [nitely/Spirit#239]
I'm not sure how mistune is being used in the project, but the latest version of spirit depends on mistune 0.7.4 which, according to pipenv, is vulnurable to cross-site scripting attacks.

**Comment by nitely** [comment]
It's not. That issue was reported here actually. That said, we should
upgrade that dependency.

**Comment by nitely** [comment]
I mean Spirit is not vulnerable. Old mistune is.
