### ISSUE TITLE
Error: relation "spirit_rl_cache" does not existt

### ISSUE THREAD

**Issue by Soraaz** [nitely/Spirit#244]
Hi,

When i sign in or sign up with the spirit forum. I have this error

> relation "spirit_rl_cache" does not exist

Where can i create this table ?

**Comment by nitely** [comment]
Run `python manage.py createcachetable`. But the `spiritinstall` command do this, so did you follow the Spirit install instructions?

**Comment by Soraaz** [comment]
Thank. It's work. I just change the database after launch spiritinstall.
