### ISSUE TITLE
render_comments_form should accept context

### ISSUE THREAD

**Issue by andreynovikov** [nitely/Spirit#249]
I am customizing Spirit templates as I need some user-based behavior in comments form. In most cases it is included in other templates and everything works fine. But in one case it is rendered via tag:
https://github.com/nitely/Spirit/blob/03cdfd2d66ddca2d8a34438321cd17e4129db29b/spirit/comment/tags.py#L16

In that case I can not access current user inside the template. It would be nice if you will pass `context` (or `request`) there so I can use `request.user`.

**Comment by nitely** [comment]
If you are in a hurry, make a PR and I'll merge it.
