### ISSUE TITLE
Separate forum and site styles

### ISSUE THREAD

**Issue by andreynovikov** [nitely/Spirit#251]
Currently all CSS rules are put together intended to provide separate forum site. In that case it is extremely hard to integrate forum into existing project. It would be nice if you will separate minimum required styling for forum and site-wide optional styles. It would be also nice if you will put forum styles into separate namespace (with the help of the custom prefix for class and id names).

**Comment by nitely** [comment]
> It would be nice if you will separate minimum required styling for forum and site-wide optional styles.

Not sure what you mean by this.

> It would be also nice if you will put forum styles into separate namespace (with the help of the custom prefix for class and id names).

Yeah, this can be more or less easily done. I have to move all global styling first (html, body, etc), otsde the Spirit namespace/prefix, then I can add the namespace.

I guess this is what you mean by "site-wide optional styles". But the global styling is required, cause usually they are things like resetting the style for every browser. Not sure if I can just add that to a namespace, but maybe I can...

**Comment by andreynovikov** [comment]
There are styles already for body, header, table, p, ul, ol and other general elements according to the site design. And they are already managed by sass/less. So it would be good to have Spirit styles as separate sass file without any global styles, headers and navigation.

As you provide solid solution it's nice to have out-of-the-box fully functioning site. But styling for that site (like resetting the style) should be defined in separate sass file.

**Comment by nitely** [comment]
I'll work on improving the Spirit specific styles vs global styles.
However, I still want a single CSS file that has everything. But I think
also having an extra Spirit specific styles file is doable, altough it
won't look good (it may even look broken) without the reset, etc global
site style.

**Comment by andreynovikov** [comment]
Yes, you can have single CSS because it's generated anyway, but please make a separate SASS.

**Comment by nitely** [comment]
This is implemented in master. I did not separate the global style from Spirit style, though. There are virtually no global styles now. The `html` does set a `background-color`, but you don't want to change that, unless you want to, in which case just override it.
