### ISSUE TITLE
Downgrade Mistune or Show NbConvert==5.3.1 in  requirements.txt

### ISSUE THREAD

**Issue by jelizaga3-gatech** [nitely/Spirit#255]
I received the following errors when trying to run pip install -r requirements

`django-spirit 0.7.0 has requirement mistune==0.7.4, but you'll have mistune 0.8.4 which is incompatible.`

`nbconvert 5.4.0 has requirement mistune>=0.8.1, but you'll have mistune 0.7.4 which is incompatible.`

See: `Upgrade mistune dependency PR #705`
https://nbconvert.readthedocs.io/en/latest/changelog.html#testing-docs-and-builds

**Comment by jelizaga3-gatech** [comment]
See PR #256

**Comment by nitely** [comment]
what the heck is nbconvert and why would Spirit add it as a dependency? what should be done here is to update mistune

**Comment by jelizaga3-gatech** [comment]
Agreed. My bad. There as something going on in my own "fresh" environment.
