### ISSUE TITLE
Any possibility for MathJax support for science forums?

### ISSUE THREAD

**Issue by karnakitab** [nitely/Spirit#261]
Is there any possibility to support MathJax/LaTeX to write mathematics equations/formula in posts?

**Comment by nitely** [comment]
Yes, there is a mistune plugin. It's just a pip install, IIRC.

**Comment by nitely** [comment]
Here it's https://github.com/lepture/mistune-contrib . But it't not just pip install, it requires modifing the code and adding that mixin class to the renderer. Ok, I'll add support for those contrib plugins later, so it's just a pip install and some setting.

**Comment by karnakitab** [comment]
Thanks a lot @nitely ! I shall give it a try.

**Comment by nitely** [comment]
Apparently no plugin is needed. Just add the MathJax script. However, markdown symbols mus be cape (such as `\*`, `\*\*`, etc). But it works. I added the MathJax script to the `admin -> basic settings -> footer snippet` and it just works.

**Comment by nitely** [comment]
Nevermind, the plugin is required to allow inline math notation and to avoid escaping markdown symbols.

**Comment by nitely** [comment]
Well, I've bad news and good news. Bad news: I tried to implement support for mistune.contrib and plugins but mistune has too many quirks to make it pain free. Good news: I ended up adding support for mathjax/latex and it's better than the plugin. If you can give #262 a try in your local machine, it would be great. You'll have to add the mathjax library to the footer template (override spirit/_footer.html) or to the "footer snipped" text-box in the admin -> basic settings.

```
<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```

**Comment by nitely** [comment]
When the next release is out, you'll just have to add `ST_MATH_JAX = True` to settings. That's it.
