### ISSUE TITLE
Spirit 0.5 integration into Project

### ISSUE THREAD

**Issue by pythonjedi2** [nitely/Spirit#268]
I am now running django 1.4.3 and each time I upgrade to django 1.11 my project does not run at all and pushes some form of exception. Is there a manual work around to integrate the spirit forum into my project using django 1.4.3?

**Comment by nitely** [comment]
I don't think so. There are too many changes between those two versions.
You can try upgrading one major version at a time , i.e 1.5, 1.6, etc so
you get warned about deprecations...

**Comment by pythonjedi2** [comment]
Nice thanks much Nitely. I tried to upgrade but then it it does not run my project. Can I send you the zip file for you take a look at this? I have been at this for agents

**Comment by pythonjedi2** [comment]
I will try to upgrade to 1.5 right now and see if works

**Comment by pythonjedi2** [comment]
I got it upgraded to 1.7.11 any pointers with the integration now? Spirit it really awesome and would like to use it

**Comment by nitely** [comment]
I'm pretty sure Spirit use some features that were added in recent Django
versions. You can try some old Spirit version. However, ir used to be a lot
harder to integrate Spirit back then, I can't help you with that.
