### ISSUE TITLE
JPG orientation

### ISSUE THREAD

**Issue by urielarg** [nitely/Spirit#270]
EXIF rotation kept, but not displayed accordingly.
![cebollita](https://user-images.githubusercontent.com/746556/57200273-e1b96a00-6f81-11e9-9de5-fb6fd977bf1c.jpg)
Github itself behaves the same...

**Comment by nitely** [comment]
Most web-browser have [fix this issue](https://caniuse.com/css-image-orientation). So there's nothing to do here, IMO.
