### ISSUE TITLE
E-mail is taken error

### ISSUE THREAD

**Issue by grwhumphries** [nitely/Spirit#273]
I've installed spirit alongside my existing app and hooked into a pre-existing database. 

When I try to sign up as a new user, I'm getting an 'E-mail is taken' error, though that e-mail (and any other I have tried) does not exist in the database.

**Comment by nitely** [comment]
Spirit has a `ST_CASE_INSENSITIVE_EMAILS` setting, default is `True`. So trying different casing won't work if that's what you're trying. Otherwise, the email must exists... are you sure it does not?

**Comment by grwhumphries** [comment]
Yeah - I'm sure it doesn't exist. I've also been getting a "User has no st" error? Could the two be linked?

**Comment by nitely** [comment]
> Could the two be linked?

No, I don't think so. I'll try to reproduce it, give a few minutes.

Spirit creates a user profile when a user is created. So, you'll have to create profiles for existing users. I think I can create the profile at log-in, if it does not exist :thinking: 

Unrelated: set `ST_CASE_INSENSITIVE_USERNAMES` to `False`. If you are using Spirit auth, you probably want that setting off. It's better to set it on for new projects, but probably not a good idea for existing projects.

**Comment by grwhumphries** [comment]
I did see that there's supposed to be a migration for creating new spirit user profiles? Or has that not been put together yet?

**Comment by nitely** [comment]
Oh, that's right. [There is such migration](https://github.com/nitely/Spirit/blob/master/spirit/user/migrations/0004_auto_20150731_2351.py). Weird, I've no idea what's going on then.

**Comment by grwhumphries** [comment]
Any reason why the migration wouldn't have worked? it doesn't seem to have run when I ran python manage.py spiritinstall

**Comment by nitely** [comment]
It should just work. Try this:

```
python manage.py migrate
python manage.py createcachetable
python manage.py collectstatic
```

^ That's what `spiritinstall` does. Did you add all spirit apps to `INSTALLED_APPS`? how did you integrated Spirit into your project? I think the best way to integrate it is to create a new project following the install instructions, then copying/merging all Spirit settings into the existing project settings.

**Comment by grwhumphries** [comment]
I have a wagtail project that I've started with 
`wagtail start mysite`
I've got an existing auth_user table from a different website that I'm pulling over in order to not have to get those users to re-do their accounts.

**Comment by nitely** [comment]
> I have a wagtail project that I've started with
wagtail start mysite
I've got an existing auth_user table from a different website that I'm pulling over in order to not have to get those users to re-do their accounts.

I don't quite get it, but Spirit is just a set of apps. It can co-exist with any other apps (including wagtail). There is no need to have two separate DB or anything like that. In fact, that will probably back fire at some point.

Those setting seem ok. 

> but the migration didn't work.

What do you mean by this? Did it tries to run the migrations? what's the output of `manage.py migrate`?

**Comment by nitely** [comment]
Can you copy paste here the `settings/base.py` content?

**Comment by grwhumphries** [comment]
Hmmm... going to close out this issue..  I started from scratch and did it again and the issues seems to have resolved itself. There must have been a funny migration in my attempts to figure this out the first time.  Best I can figure out, in my first goes, the django migration that adds 'last_login" = null didn't run.. or may have been overwritten by something.  Then the migration that brings the user profiles over to spirit didn't run or was overwritten.

**Comment by nitely** [comment]
That's very extrange. Even if no data migration ran for some weird reason, all the code does is something like `User.objects.filter(email=email).exists()` and if that returns True then this error is raised. It does not use any Spirit model for this.

I guess we will never know what the issue was.

**Comment by grwhumphries** [comment]
Forever a mystery like bigfoot or the loch ness monster
