### ISSUE TITLE
Redirect on topic delete

### ISSUE THREAD

**Issue by grwhumphries** [nitely/Spirit#274]
I notice that when a topic is deleted by clicked on "delete topic", the redirect is back to the comment that was just deleted.  I'm wondering if it would be more intuitive to re-direct this back to the main list of topics?

**Comment by nitely** [comment]
All topic actions should redirect to the topic, so you can apply a new action, like undo the delete. But there should be some hint about the new state, like an icon next to the title or a red highlight or something, yeah :+1:

**Comment by grwhumphries** [comment]
Okay - I see what you were going for.  Yeah for sure a highlight or some sort of indication that the action completed successfully would be useful
