### ISSUE TITLE
Facebook Social_share link doesn't work. 

### ISSUE THREAD

**Issue by grwhumphries** [nitely/Spirit#276]
The get_facebook_share_url code wasn't working for me. I kept getting an error.  I've updated this: 

@register.simple_tag(takes_context=True)  
def get_facebook_share_url(context, url, title):  
    request = context['request']  
    params = [('s', "100"),  
              ('p[url]', request.build_absolute_uri(url)),  
              ('p[title]', title)]  
    return FACEBOOK_URL % urlencode(params)
  
To this:

@register.simple_tag(takes_context=True)  
def get_facebook_share_url(context, url):  
    request = context['request']  
    params = [('u',request.build_absolute_uri(url))]  
    return FACEBOOK_URL % urlencode(params)  

This seems to work fine.   Also, I've added the Linkedin equivalent in here, which is more appropriate as GPlus is basically dead.   

LINKEDIN_URL = "https://www.linkedin.com/sharing/share-offsite/?%s"  

@register.simple_tag(takes_context=True)  
def get_linkedin_share_url(context,url):  
    request = context['request']  
    params = [('url', request.build_absolute_uri(url)), ]  
    return LINKEDIN_URL % urlencode(params)

**Comment by grwhumphries** [comment]
Oh also, the link to the facebook sharer should start with https:// not http

**Comment by nitely** [comment]
Hey!

Great! are you interested in creating a PR for this changes?

**Comment by grwhumphries** [comment]
I'd be happy to figure out how to do it - not done PRs before as I'm usually just puttering around with my own code.

**Comment by nitely** [comment]
It seems github has a way to edit a file from its UI and create a PR... I've never tried it since I use git, but it should work.

Let me know if you figure out a way or want me to make the changes myself instead.

**Comment by nitely** [comment]
Ah, silly me, you have some projects and forks, so I'm sure you will manage
