### ISSUE TITLE
spirit_user migration fails 

### ISSUE THREAD

**Issue by CarlHostetter-NASA** [nitely/Spirit#277]
Applying migrations to my Spirit-ed Django project is failing:

`Operations to perform:
  Apply all migrations: admin, auth, contenttypes, djconfig, sessions, spirit_category, spirit_comment, spirit_comment_bookmark, spirit_comment_flag, spirit_comment_history, spirit_comment_like, spirit_comment_poll, spirit_topic, spirit_topic_favorite, spirit_topic_notification, spirit_topic_private, spirit_topic_unread, spirit_user, website
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying djconfig.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying spirit_category.0001_initial... OK
  Applying spirit_category.0002_auto_20150728_0442... OK
  Applying spirit_category.0003_category_is_global... OK
  Applying spirit_category.0004_category_color... OK
  Applying spirit_category.0005_category_reindex_at... OK
  Applying spirit_category.0006_auto_20190120_0406... OK
  Applying spirit_category.0007_auto_20190304_2115... OK
  Applying spirit_category.0008_auto_20190814_2124... OK
  Applying spirit_topic.0001_initial... OK
  Applying spirit_comment.0001_initial... OK
  Applying spirit_comment.0002_auto_20150828_2003... OK
  Applying spirit_comment.0003_auto_20151115_0400... OK
  Applying spirit_comment.0004_auto_20160315_2021... OK
  Applying spirit_comment_bookmark.0001_initial... OK
  Applying spirit_comment_bookmark.0002_auto_20150828_2003... OK
  Applying spirit_comment_flag.0001_initial... OK
  Applying spirit_comment_flag.0002_auto_20150828_2003... OK
  Applying spirit_comment_history.0001_initial... OK
  Applying spirit_comment_like.0001_initial... OK
  Applying spirit_comment_like.0002_auto_20150828_2003... OK
  Applying spirit_comment_poll.0001_initial... OK
  Applying spirit_comment_poll.0002_auto_20190304_2115... OK
  Applying spirit_topic.0002_auto_20150828_2003... OK
  Applying spirit_topic.0003_topic_reindex_at... OK
  Applying spirit_topic_favorite.0001_initial... OK
  Applying spirit_topic_favorite.0002_auto_20150828_2003... OK
  Applying spirit_topic_notification.0001_initial... OK
  Applying spirit_topic_notification.0002_auto_20150828_2003... OK
  Applying spirit_topic_private.0001_initial... OK
  Applying spirit_topic_private.0002_auto_20150828_2003... OK
  Applying spirit_topic_unread.0001_initial... OK
  Applying spirit_topic_unread.0002_auto_20150828_2003... OK
  Applying spirit_user.0001_initial... OK
  Applying spirit_user.0002_auto_20150728_0447... OK
  Applying spirit_user.0003_auto_20150728_0448... OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "spirit_user_userprofile" does not exist
LINE 1: ...r"."date_joined" FROM "auth_user" LEFT OUTER JOIN "spirit_us...`

I installed spirit with:

`pip install django-spirit`

Here's the list of tables:

`postgres=# \dt
                            List of relations`
 Schema |                    Name                     | Type  |  Owner   
--------+---------------------------------------------+-------+----------
 public | auth_group                                  | table | postgres
 public | auth_group_permissions                      | table | postgres
 public | auth_permission                             | table | postgres
 public | auth_user                                   | table | postgres
 public | auth_user_groups                            | table | postgres
 public | auth_user_user_permissions                  | table | postgres
 public | django_admin_log                            | table | postgres
 public | django_content_type                         | table | postgres
 public | django_migrations                           | table | postgres
 public | django_session                              | table | postgres
 public | djconfig_config                             | table | postgres
 public | spirit_category_category                    | table | postgres
 public | spirit_comment_bookmark_commentbookmark     | table | postgres
 public | spirit_comment_comment                      | table | postgres
 public | spirit_comment_flag_commentflag             | table | postgres
 public | spirit_comment_flag_flag                    | table | postgres
 public | spirit_comment_history_commenthistory       | table | postgres
 public | spirit_comment_like_commentlike             | table | postgres
 public | spirit_comment_poll_commentpoll             | table | postgres
 public | spirit_comment_poll_commentpollchoice       | table | postgres
 public | spirit_comment_poll_commentpollvote         | table | postgres
 public | spirit_topic_favorite_topicfavorite         | table | postgres
 public | spirit_topic_notification_topicnotification | table | postgres
 public | spirit_topic_private_topicprivate           | table | postgres
 public | spirit_topic_topic                          | table | postgres
 public | spirit_topic_unread_topicunread             | table | postgres
 public | spirit_user_userprofile                     | table | postgres
`(27 rows)`

And here's the list of fields and schema of auth_user:

`postgres=# \d auth_user
                                        Table "public.auth_user"`
    Column    |           Type           | Collation | Nullable |                Default                
--------------+--------------------------+-----------+----------+---------------------------------------
 id           | integer                  |           | not null | nextval('auth_user_id_seq'::regclass)
 password     | character varying(128)   |           | not null | 
 last_login   | timestamp with time zone |           |          | 
 is_superuser | boolean                  |           | not null | 
 username     | character varying(150)   |           | not null | 
 first_name   | character varying(30)    |           | not null | 
 last_name    | character varying(150)   |           | not null | 
 email        | character varying(254)   |           | not null | 
 is_staff     | boolean                  |           | not null | 
 is_active    | boolean                  |           | not null | 
 date_joined  | timestamp with time zone |           | not null | 
`Indexes:
    "auth_user_pkey" PRIMARY KEY, btree (id)
    "auth_user_username_key" UNIQUE CONSTRAINT, btree (username)
    "auth_user_username_6821ab7c_like" btree (username varchar_pattern_ops)
Referenced by:
    TABLE "auth_user_groups" CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "auth_user_user_permissions" CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "django_admin_log" CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_comment_bookmark_commentbookmark" CONSTRAINT "spirit_comment_bookm_user_id_b31a0d88_fk_auth_user" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_comment_comment" CONSTRAINT "spirit_comment_comment_user_id_0f9dbd41_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_comment_flag_commentflag" CONSTRAINT "spirit_comment_flag__moderator_id_1eb69535_fk_auth_user" FOREIGN KEY (moderator_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_comment_flag_flag" CONSTRAINT "spirit_comment_flag_flag_user_id_ffbf846e_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_comment_like_commentlike" CONSTRAINT "spirit_comment_like__user_id_85e21014_fk_auth_user" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_comment_poll_commentpollvote" CONSTRAINT "spirit_comment_poll__voter_id_7fd9a8eb_fk_auth_user" FOREIGN KEY (voter_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_topic_favorite_topicfavorite" CONSTRAINT "spirit_topic_favorit_user_id_e406cc12_fk_auth_user" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_topic_notification_topicnotification" CONSTRAINT "spirit_topic_notific_user_id_a9d2003a_fk_auth_user" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_topic_private_topicprivate" CONSTRAINT "spirit_topic_private_user_id_682c6ef5_fk_auth_user" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_topic_topic" CONSTRAINT "spirit_topic_topic_user_id_5d0151a9_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_topic_unread_topicunread" CONSTRAINT "spirit_topic_unread__user_id_f5a459f5_fk_auth_user" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
    TABLE "spirit_user_userprofile" CONSTRAINT "spirit_user_userprofile_user_id_40907b15_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED`

**Comment by nitely** [comment]
How can I reproduce this?

**Comment by CarlHostetter-NASA** [comment]
Let me explain a bit how I'm trying to use Spirit.

I have an existing Django project and website app, and want to add Spirit as a peer forum app to the project:

    project
        website
        forum (Spirit)

I also want to keep the forum (Spirit) database separate from the website database. To that end, I've defined to databases:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres', 
            'USER': 'postgres', 
            'PASSWORD': ADMIN_PASSWORD,
            'HOST': 'shared_db',
        }
        ['forums'] = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME' : 'postgres', 
            'USER': 'postgres', 
            'PASSWORD': ADMIN_PASSWORD,
            'HOST': 'forums_db',
        }
    }

I then defined and added a Django Router class that shunts all Spirit-specific models, fields, and relationships to the forums_db:

class ForumsRouter:

    """
    A router to control all database operations on models in the
    forums application.
    """

    def db_for_read(self, model, **hints):
        """
        Attempts to read forums models go to the forums database.
        """
        if model._meta.app_label == 'forums' or model._meta.app_label.startswith('spirit'):
            return 'forums'
        return None

    def db_for_write(self, model, **hints):
        """
        Attempts to write forums models go to the forums database.
        """
        if model._meta.app_label == 'forums' or model._meta.app_label.startswith('spirit'):
            return 'forums'
        return None

    def allow_relation(self, obj1, obj2, **hints):
        """
        Allow relations if a model in the forums app is involved.
        """
        if (obj1._meta.app_label == 'forums' or obj1._meta.app_label.startswith('spirit')) or \
            (obj2._meta.app_label == 'forums' or obj2._meta.app_label.startswith('spirit')) :
            return True
        return None

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        """
        Make sure the forums app only appears in the forums database.
        """
        if app_label == 'forums' or app_label.startswith('spirit'):
            return db == 'forums'
        return None

For the most part, this appears to work: the right models, fields, and relationships end up in the right place, except for that one migration that fails as above.

I wonder whether Django's migration is somehow looking in the wrong database (i.e., the default instead of forums_db) for the relationship it thinks is missing?

**Comment by nitely** [comment]
> I wonder whether Django's migration is somehow looking in the wrong database (i.e., the default instead of forums_db) for the relationship it thinks is missing?

Yeah, that'd also be first guess. The next migration (which I think is causing the error) uses django's user model, so the app label is something like `auth` or whatever, which will use the default DB. I'll look into it later.

However, since you're not sharing the DB, I think you'd be better off running two django instances, either that or share the DB.

**Comment by CarlHostetter-NASA** [comment]
OK, I can do that. Thanks for your attention!

**Comment by CarlHostetter-NASA** [comment]
P.S. While I have your attention, I've been looking for some way to change the "title" at the top of the forum pages from "Spirit" to our own project name (so that users more readily see it as our project's discussion forum). Is there a way to do this? Again, thanks!

**Comment by nitely** [comment]
The title can be changed in `/st/admin/config/`
