### ISSUE TITLE
cannot change password when forget

### ISSUE THREAD

**Issue by catmemo** [nitely/Spirit#302]
Server Error (500) was got when tried to reset password in https://community.spirit-project.com/user/password-reset/

**Comment by catmemo** [comment]
@nitely Could you please help to check? Thanks~

**Comment by nitely** [comment]
I can't reproduce the issue.

**Comment by nitely** [comment]
Ah, It's on password reset complete. I just fixed it https://github.com/nitely/Spirit/commit/a10de8014bacd9f3009cf568b791561b2ab0aa20

Thanks!

**Comment by catmemo** [comment]
> Ah, It's on password reset complete. I just fixed it [a10de80](https://github.com/nitely/Spirit/commit/a10de8014bacd9f3009cf568b791561b2ab0aa20)
> 
> Thanks!

My pleasure~

**Comment by catmemo** [comment]
@nitely 
Sorry but I failed again~
my email is : 2103559134@qq.com

I actually received the "Password reset on community.spirit-project.com" email.
And then I clicked on below link and got into the password reset form successfully.
https://community.spirit-project.com/user/reset/Nzcx/ag5is2-c78c5b290693f12634dd6f6f55a83d54/

But "server error 500" was returned after I filled the new password and clicked submit again.
Do you have any suggestions? Thanks~

**Comment by nitely** [comment]
I just updated the spirit-project's Spirit version. It should be working now.

btw, the password should have been changed even if you get that error.

**Comment by catmemo** [comment]
> I just updated the spirit-project's Spirit version. It should be working now.
> 
> btw, the password should have been changed even if you get that error.

Ciao nitely, thank you for your quickly response~
