### ISSUE TITLE
Search function not work

### ISSUE THREAD

**Issue by catmemo** [nitely/Spirit#304]
Followed below steps:

pip install django-spirit
spirit startproject mysite
cd mysite
python manage.py spiritinstall
python manage.py createsuperuser
python manage.py runserver

But return nothing when searching. Could you please help to check? Thks~
@nitely

**Comment by nitely** [comment]
Read this: https://spirit.readthedocs.io/en/latest/task_manager.html

> Functionality that requires a task manager includes: search indexation.

also email notfications. However, for very small sites you may use the real time indexation (it'll increase the time it takes to post/comment/create topics), see https://django-haystack.readthedocs.io/en/master/signal_processors.html#realtime-realtimesignalprocessor

**Comment by catmemo** [comment]
> 

Thank you very much!

**Comment by catmemo** [comment]
Ciao,


As you said, we can use haystack to synchronize but it seems that base.py in settings already done it after we create a new project following proper steps provided.
And then we created a topic but searched without anything response. That's the problem encountered. Could you please help？













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nitely/Spirit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月25日(星期六) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nitely/Spirit] Search function not work (Issue #304)





 
Read this: https://spirit.readthedocs.io/en/latest/task_manager.html
  
Functionality that requires a task manager includes: search indexation.
  
also email notfications. However, for very small sites you may use the real time indexation (it'll increase the time it takes to post/comment/create topics), see https://django-haystack.readthedocs.io/en/master/signal_processors.html#realtime-realtimesignalprocessor
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nitely** [comment]
try running `python manage.py rebuild_index` that should index existing/old topics, then search. If it works, then set up a task manager https://spirit.readthedocs.io/en/latest/task_manager.html , not sure why the realtime search does not work.

If that command does not work, then there is something wrong with your setup.

**Comment by nitely** [comment]
btw, are you trying things in a local machine or what?

**Comment by catmemo** [comment]
> 

Local windows 10 pc

**Comment by nitely** [comment]
ok, the whoosh search engine that comes configured by default should probably work (I'm a Linux user, not sure)

**Comment by catmemo** [comment]
> ok, the whoosh search engine that comes configured by default should probably work (I'm a Linux user, not sure)

The command works and indexing 2 topics, but when I tried to search something response with nothing again

**Comment by catmemo** [comment]
> 

Actually, I also deploy it to Ubuntu Apache2 and got the same results.

**Comment by nitely** [comment]
> The command works and indexing 2 topics, but when I tried to search something response with nothing again.

since the topics got indexed, the search should work. Not sure why it does not. Are you searching full words contained in the comments/topic title?

> not sure why the realtime search does not work

it does not work, because it requires a task manager. If you remove this check, it should work:
https://github.com/nitely/Spirit/blob/01e579948c9f4df397085d0fa849137f79651aac/spirit/core/tasks.py#L107

> And it still does not work after I set up the huey task manager.

if `python manage.py rebuild_index` says it indexed some topics, and they do not show in the search result, then the search just won't work any other way. There is something wrong with your setup, I don't know what it is.

I use the prod.py setting without any significant change and it works for me.

**Comment by nitely** [comment]
one thing you can check is if you have multiple `st_search` folders, that's where the whoosh index is stored, if you have more than one it could mean you are indexing the topics in one place, but the server is reading the index from another place.

**Comment by catmemo** [comment]
> > The command works and indexing 2 topics, but when I tried to search something response with nothing again.
> 
> since the topics got indexed, the search should work. Not sure why it does not. Are you searching full words contained in the comments/topic title?
> 
> > not sure why the realtime search does not work
> 
> it does not work, because it requires a task manager. If you remove this check, it should work:
> 
> https://github.com/nitely/Spirit/blob/01e579948c9f4df397085d0fa849137f79651aac/spirit/core/tasks.py#L107
> 
> > And it still does not work after I set up the huey task manager.
> 
> if `python manage.py rebuild_index` says it indexed some topics, and they do not show in the search result, then the search just won't work any other way. There is something wrong with your setup, I don't know what it is.
> 
> I use the prod.py setting without any significant change and it works for me.

As you see, I have 3 topics now and when I searched "test" it works well. But failed when searching "LOG".
![image](https://user-images.githubusercontent.com/26922437/148204238-795ac97b-31fa-4473-971e-d81993d41f1c.png)

**Comment by nitely** [comment]
Search won't find partial words. IIRC, I was working on searching partial words, but the generated index was huge, it went from a few MBs to many GBs. I thought there was a setting to turn this on, but there is not. Anyway, the reason you cannot find LOG is because it's not separated by spaces (ie: it's not considered a whole word).

I made a library to splitunicode words a while ago, but in Nim https://github.com/nitely/nim-segmentation
it would separate that string as ``["如", "何", "抓", "取", "LOG"]`, not sure if that's correct, or we need something like the NLKT, or just an option to enable partial words matching.

**Comment by catmemo** [comment]
> 

Yes, it's correct.

**Comment by nitely** [comment]
Reopening so I'll fix it

**Comment by catmemo** [comment]
> Reopening so I'll fix it

Thanks for your working!

**Comment by nitely** [comment]
I've added support for Ngram index (search on Asian languages).

The changes is unreleased, so you'll need to install with:

```
pip install git+https://github.com/nitely/Spirit.git
```

then add this to your settings:

```
ST_NGRAM_SEARCH = True
```

you'll need to rebuild the search index:

```
python manage.py rebuild_index
```

and restart the server.

Last time I tried this it generated a huge index, but it works.
