### ISSUE TITLE
Upgrade Django to the latest 3.2.14 security patch if you can; otherwise this is not usable anymore.

### ISSUE THREAD

**Issue by shaenr** [nitely/Spirit#309]

**Comment by shaenr** [comment]
I actually just realized I could get it to work with 2.2.13.... LTS :)

**Comment by WMRamadan** [comment]
Should probably keep requirements.txt at `Django==3.2.*`

**Comment by nitely** [comment]
I just released v0.13 which supports django 3.2, and 4.2
remember to read the upgrade instructions if needed https://spirit.readthedocs.io/en/latest/upgrade.html
