### ISSUE TITLE
Would it be better to index Comment rather than Topic?

### ISSUE THREAD

**Issue by sureshvv** [nitely/Spirit#326]
Currently Search returns the Topic but the search item is buried deep inside it - so one has to do a Find in page using the browser.

**Comment by nitely** [comment]
If you want to find all topics talking about X then the current search is
fine.

Returning comments and searching on a single topic is missing functionality.

**Comment by sureshvv** [comment]
Can you guide me on how to implement this missing functionality? I would like to retrieve individual comments matching the search.

**Comment by nitely** [comment]
It's a lot of work. I think most search functionality lives in https://github.com/nitely/Spirit/tree/master/spirit/search . You'll need to add the comment version of it. Things like a [search index](https://github.com/nitely/Spirit/blob/master/spirit/search/search_indexes.py), views, forms, urls, templates, etc.

For a comment you'll have fields like text (this field must contain the comment text, the search index will use it for searching on it, and it's generated by a [template like this](https://github.com/nitely/Spirit/blob/master/spirit/search/templates/search/indexes/spirit_topic/topic_text.txt)  , see the [haystack docs](https://django-haystack.readthedocs.io/en/master/)), topic_id, and is_removed at least.

**Comment by nitely** [comment]
Also, there is a [task for indexing topics](https://github.com/nitely/Spirit/blob/069e82ae07266d1748c5497dc7e22a4d2b46654c/spirit/core/tasks.py#L104) every time one is created [here](https://github.com/nitely/Spirit/blob/069e82ae07266d1748c5497dc7e22a4d2b46654c/spirit/comment/utils.py#L19). You'll need to do the same for comments.

**Comment by sureshvv** [comment]
For an initial implementation, I was able to modify spirit.search.views to extract comments from the search results and find only the matching comments and display them. May not scale well for large sites.
