### ISSUE TITLE
How do I make Search available for anonymous users?

### ISSUE THREAD

**Issue by sureshvv** [nitely/Spirit#330]
Is there a setting for this?

**Comment by nitely** [comment]
there is no setting for this. I think you'd need to remove this line https://github.com/nitely/Spirit/blob/069e82ae07266d1748c5497dc7e22a4d2b46654c/spirit/search/views.py#L29

**Comment by sureshvv** [comment]
I also updated the templates so search is available for anonymous users. See https://cp.vplan.in/cp
