### ISSUE TITLE
TypeError at yt_paginator.py

### ISSUE THREAD

**Issue by CheapSeth** [nitely/Spirit#43]
I just noticed something strange at yt_paginator.py, line 36.
A TypeError was throwed at line 36 with the message "unsupported operand type(s) for *: 'int' and 'NoneType'".

It happened just after the installation, while I was creating the first categories.
I fixed with an ugly

```
if not number: number = 1
```

Is it a real issue?

**Comment by nitely** [comment]
I've seen it before, It happens when the `apps.ready()` is not called. I remember restarting the server and the error was gone... I was not able to reproduce it again.

Can you reproduce it? what django version are you running?

**Comment by CheapSeth** [comment]
I am running Django 1.7.7 and python 3.4 (in a virtualenv).

I am trying to reproduce it but il looks like it doesn't happen when using the development server. I was using nginx+gunicorn when the TypeError showed up.

**Comment by nitely** [comment]
If you are able to reproduce it, let me know.

I'm almost sure what the problem is... it's a race condition in the `djconfig` library. It can only happen in the first request (second actually) after you start the server, while the first request is populating the config cache, the second request will try to use it and it'll return None (when accessing the `config.topics_per_page` in this case).

**Comment by CheapSeth** [comment]
I was able to reproduce it:

Create a fresh virtualenv (python 3), git clone the latest master branch of spirit, install all the requirements via pip install -r, follow the installation instructions described in the README.md
’’’
manage.py migrate
manage.py createcachetable spirit_cache
manage.py collectstatic
’’’

launch a gunicorn server

’’’
gunicorn project.wsgi
’’’

Using an administrator account, navigate through the admin panel and create some categories. The TypeError sometimes happen when returning to the forum index. Restarting gunicorn is indeed a temporary solution.

(Sorry if that is not clear enough, this is my first _real_ bug report)

**Comment by nitely** [comment]
It has to be that race condition... I can't seem to reproduce this :sweat_smile: 

Can you run `pip install django-djconfig --upgrade` and let me know if it keeps happening?
You may have to run `python manage.py migrate djconfig --fake-initial` afterwards or just remove your database and migrate everything again.

**Comment by nitely** [comment]
I found what's causing this: https://docs.djangoproject.com/en/1.7/ref/settings/#timeout

The cache keys will expire after five minutes! :joy: 

Thank you! I will release a fix ASAP.
