### ISSUE TITLE
Replace custom user mgmt with Spirit's

### ISSUE THREAD

**Issue by Robrechtc** [nitely/Spirit#44]
Hey again! It's been a while :p 

So I'm ready to integrate Spirit in my project. In doing so, I'd like to use the user management you wrote as mine was only a temporary solution meant for local purposes only. I'm not sure how to go about replacing it, though - I've tried importing your views for logging in but then I get a template error on registration/login.html. How would one go about doing this? 

Many thanks in advance!

**Comment by nitely** [comment]
Hi!

Can you elaborate about what you are trying to achieve? I get that you want
to use the Spirit login, why do you want to import it into your own view?

FWIW, I'm dropping the custom user model, next Spirit will use a oneToOne
field to extend the user profile. I'm working on this in the experimental
branch.

**Comment by Boogymanx** [comment]
Well, I had my own 'accounts' app which had a login, logout and register view but (for example) no e-mail confirmation, no forgot password, etc. On my index page I have a login and registration form, and I'd like those to POST to your forms, however looking at your source code and your urls/user.py, I can't seem to find them.

**Comment by nitely** [comment]
Django has all that features built-in (except for the email verification).
So, some of them are imported in the urls/user.py file (ie: password
reset), you can find the rest in views/user.py.

You could *display* the login and registration forms (forms/user.py) and
then in your template, POST to the spirit views.
<form target='url(spirit::user-login)'> (non working code, but you get the
idea)

**Comment by Boogymanx** [comment]
Sorry for not replying earlier - I fell asleep. I currently have allauth working on my project. If I install from the master branch, can I already extend my user? 
 Many thanks for the help!

**Comment by nitely** [comment]
Allauth has all those features you want out of the box, isn't it? (password reset, email confirmation...) I think you should use a single auth system. You can replace the Spirit auth system by allauth.

> If I install from the master branch, can I already extend my user?

Yes, use a `OneToOneField` to extend it, that's the easy way.

**Comment by Boogymanx** [comment]
I want to use a single auth system :) that's why I installed allauth. How would I replace your auth system? And what OneToOneField do I need to add? :p Many thanks again for your reply! :D

**Comment by nitely** [comment]
> How would I replace your auth system?

Set `LOGIN_URL` in your settings.py (ie: `LOGIN_URL = 'allauth-login'`, that's probably not the allauth url name, just an example).
Change the user-login url in Spirit's `templates/spirit/_header.html` (override that template).
I think that's it.

> And what OneToOneField do I need to add?

```
class MyUserExtension(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='myuser')
    foobar = models.CharField(max_length=100)
```

Then you can do:

```
from django.contrib.auth import get_user_model

User = get_user_model()


def allusers(request):
    users = User.objects.all()
    # ...


@login_required
def myview(request):
    # you can access MyUserExtension properties within the template. ie: user.myuser.foobar
    # ...


@login_required
def myuser_update(request):
    if request.method == 'POST':
        form = MyUserForm(data=request.POST, instance=request.user.myuser)

        if form.is_valid():
            form.save()
            return redirect(reverse('...'))
    else:
        form = MyUserForm(instance=request.user.myuser)
```

**Comment by Boogymanx** [comment]
Ah, I already have a model that extends my User :) I'll replace those things and then see what happens when I use my model. Thanks for the reply!

**Comment by Boogymanx** [comment]
I have extended your AbstractForumUser, however I'm getting an error on the username field - there is no 'username' field on my e-mail, but the USERNAME_FIELD is the e-mail they use to sign up. However, I'd like to display their first name when posting. Do you know how I would go about doing that?

**Comment by nitely** [comment]
Spirit requires an username field. If you don't have one, it won't work.

Try this:

```python
class MyUser(AbstractBaseUser, PermissionsMixin, AbstractForumUser):
    username = models.CharField(_("username"), max_length=30, blank=True)
    # ...
```

I'm not sure this will work, though.

**Comment by Boogymanx** [comment]
I (think I) fixed it by adding a username field and just putting username = first_name in my save(). However, now I'm getting another issue - Spirit doesn't find my 'accounts' app, which contains my User and UserProfiles. 

```
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/apps/registry.py", line 148, in get_app_config
    return self.app_configs[app_label]
KeyError: 'accounts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/state.py", line 84, in render
    model = self.apps.get_model(lookup_model[0], lookup_model[1])
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/apps/registry.py", line 150, in get_app_config
    raise LookupError("No installed app with label '%s'." % app_label)
LookupError: No installed app with label 'accounts'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/state.py", line 94, in render
    raise ValueError(msg.format(field=operations[0][1], model=lookup_model))
ValueError: Lookup failed for model referenced by field spirit.Comment.user: accounts.User
```

**Comment by nitely** [comment]
Did you installed your accounts app?

```python
# settings.py

from spirit.settings import *

INSTALLED_APPS += (
    'accounts',
    # ...
)

AUTH_USER_MODEL = 'accounts.MyUser'
```

**Comment by Boogymanx** [comment]
I do, this is a snippet from my settings.py: 
```
"""
Django settings for Yoonify project.

For more information on this file, see
https://docs.djangoproject.com/en/1.7/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.7/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from spirit.settings import *
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.7/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', ]


os.environ['DJANGO_SETTINGS_MODULE'] = 'conf.settings'

# Application definition

DEFAULT_APPS = (
#    'django.contrib.admin',
#    'django.contrib.auth',
#    'django.contrib.contenttypes',
#    'django.contrib.sessions',
#    'django.contrib.messages',
#    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
)

THIRD_PARTY_APPS = (
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_nyt',
    'mptt',
    'sekizai',
    'sorl.thumbnail',
    'wiki',
    'wiki.plugins.attachments',
    'wiki.plugins.notifications',
    'wiki.plugins.images',
    'wiki.plugins.macros',
)

LOCAL_APPS = (
    'accounts',
    'university_track',
    'uploader',
)

INSTALLED_APPS += DEFAULT_APPS + LOCAL_APPS + THIRD_PARTY_APPS


#MIDDLEWARE_CLASSES = (
#    'django.contrib.sessions.middleware.SessionMiddleware',
#    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
#    'django.contrib.auth.middleware.AuthenticationMiddleware',
#    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
#    'django.contrib.messages.middleware.MessageMiddleware',
#    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#)

ROOT_URLCONF = 'Yoonify.urls'

WSGI_APPLICATION = 'Yoonify.wsgi.application'

SITE_ID = 1

# Database
# https://docs.djangoproject.com/en/1.7/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #    'NAME': 'yoonify',
    #}
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'yoonify.db'),
    }
}


DATE_INPUT_FORMATS = ('%d-m-%Y', '%Y-%m-%d')

# Internationalization
# https://docs.djangoproject.com/en/1.7/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.7/howto/static-files/


STATIC_URL="/static/"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    )
#User settings

AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = True
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/BBA/1'
```

**Comment by nitely** [comment]
It seems `ST_INITIAL_MIGRATION_DEPENDENCIES` is missing.

```python
# settings.py
# ...
ST_INITIAL_MIGRATION_DEPENDENCIES = [('accounts', '0001_initial'), ]
```

**Comment by Boogymanx** [comment]
That fixed that issue :p now, however, I get an issue with is_verified: At first, I got an error saying that User has no field named 'is_verified'. If I add that on my model, though, I get this error - django.core.exceptions.FieldError: Local field 'is_verified' in class 'User' clashes with field of similar name from base class 'AbstractForumUser'. I'm not sure how to fix that and a Google search hasn't immediately proven any results either.

**Comment by nitely** [comment]
Can you show me the traceback?

`AbstractForumUser` has a `is_verified` field, so you should not add it to your user.

**Comment by Boogymanx** [comment]
```
  Applying spirit.0006_auto_20150327_0204...Traceback (most recent call last):
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/models/options.py", line 414, in get_field_by_name
    return self._name_map[name]
KeyError: 'is_verified'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/spirit/migrations/0006_auto_20150327_0204.py", line 10, in verify_active_users
    User.objects.filter(is_active=True).update(is_verified=True)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/models/query.py", line 581, in update
    query.add_update_values(kwargs)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/models/sql/subqueries.py", line 129, in add_update_values
    field, model, direct, m2m = self.get_meta().get_field_by_name(name)
  File "/home/robbie/.virtualenvs/Yoonify/lib/python3.4/site-packages/django/db/models/options.py", line 420, in get_field_by_name
    % (self.object_name, name))
django.db.models.fields.FieldDoesNotExist: User has no field named 'is_verified'
```

**Comment by nitely** [comment]
Are you extending the `AbstractForumUser` field in your `User` model? ie: `class User(AbstractBaseUser, PermissionsMixin, AbstractForumUser): #...`

**Comment by Boogymanx** [comment]
Yup, this is my User model: 
```
class User(AbstractBaseUser, AbstractForumUser):

    first_name = models.CharField(verbose_name='First name', max_length=255)
    last_name = models.CharField(verbose_name='Last name', max_length=255)
    email = models.EmailField(
        verbose_name='Email address',
        max_length=255,
        unique=True
    )
    date_of_birth = models.DateField()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    objects = UserManager()
    username = models.CharField(default='', max_length=255)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'date_of_birth']

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app 'app_label'?"
        return True

    @property
    def is_staff(self):
        return self.is_admin
```
The AbstractBaseUser isn't from Spirit, though, it's from Django if that matters

**Comment by nitely** [comment]
Try running `python manage.py makemigrations`

**Comment by Boogymanx** [comment]
Then I get No changes detected

**Comment by Boogymanx** [comment]
Someone in #django told me to print User._meta.fields in a shell, this is the output: https://dpaste.de/5qXx 
There is an is_verified field, so I don't know what the issue is. Would deleting my accounts migrations maybe fix it?

**Comment by nitely** [comment]
> Would deleting my accounts migrations maybe fix it? 

Probably yes.

**Comment by Boogymanx** [comment]
Another Django user fixed it - in my latest migration (where I had added the is_verified field), I had to add run_before = [('spirit', '0006_auto_20150327_0204').  Now it works.

**Comment by Boogymanx** [comment]
I do have another question, though - we are going to use the forum for general feedback submissions. For this, we'd like to have a popup on the main pages that allows users to submit a topic. What forms/views do I need to look at for this? Or would I be better off creating my own?

**Comment by nitely** [comment]
The topic publication is at `spirit/views/topic.py`. If you need a popup, you will be better off creating your own view (I think that's probably the only way).

**Comment by Boogymanx** [comment]
All right, I'll look at that, thanks! Spirit looks completely amazing, by the way :)  I have run into another error, though: https://dpaste.de/kxYT . I checked my settings and have all the timezone settings. Looking at my User in admin, though, I can't see a date_joined so maybe that is the issue? Although I think I set it to timezone.now() after a migration if I'm not mistaken. Thanks again for all the help!

**Comment by Boogymanx** [comment]
Also, my account doesn't appear to have Spirit admin permissions - is there any way I can set them/a command I have to run to make my user an admin user?

**Comment by nitely** [comment]
> I can't see a date_joined so maybe that is the issue?

Yes, that's the issue. I think that's the [only field missing](https://github.com/nitely/Spirit/blob/master/spirit/models/user.py#L48) in you User model.

```python
class User(AbstractBaseUser, AbstractForumUser):
    #...
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
```

> is there any way I can set them/a command I have to run to make my user an admin user?

Create an user via `python manage.py createsuperuser` command. That user will be able to set any other user as an administrator from the user profile.

**Comment by Boogymanx** [comment]
Yeah, I added the is_administrator and is_moderator to my Admin user panel and I can modify them like that. I've also added the date_joined. Everything seems to be working now, but there is one more thing I'd like to do - we have a custom dropdown in our header that has notifications (django-wiki's bundled solution, django-notifications). Is there a way to send the notifications to that dropdown? I realize this is rather vague, quite unrelated and to be honest I feel guilty about asking so much, so you can feel free to close this if you want. Thanks again for the great support! I'm definitely going to be recommending Spirit to everyone I know :)

**Comment by nitely** [comment]
I'm curious, how are you merging both notifications (django-wiki and django-notifications)?

[Here](https://github.com/nitely/Spirit/blob/master/spirit/signals/handlers/topic_notification.py) is how notifications are created. You can create custom notifications connecting to those signals, so you can use `django-notifications`. Remove the notification button from  `templates/spirit/_header.html`, you can override that template.

A simpler but ugly solution would be to show both as separate dropdowns or splitting the dropdown like this:

```
[dropdown button]
---------------------------
django notification 1  | |  <-- scrollbar
django notification 2  | |

...

spirit notification 1  | |  <-- second scrollbar
spirit notification 2  | |
---------------------------
```

**Comment by Boogymanx** [comment]
Django-notifications is built in to django-wiki :) I'll have a look at that! Will definitely need to replace the header. I'm going to add a link to Spirit in the footer though, credit where credit is due and all that :D thanks again for everything

**Comment by Boogymanx** [comment]
Just realized that django-wiki's notification system is called django-nyt, not django-notifications, my bad. While playing around with the forum my colleagues and I have noticed another issue - if we upload images, they 404. I have noticed that locally, the images do get uploaded and put in PROJECT_ROOT/spirit/ etc etc. Does this mean that I'm missing an URL or something?

**Comment by nitely** [comment]
The images are not being served. In development mode, you should set the [media url](https://github.com/nitely/Spirit/blob/master/example/project/urls.py#L30). Also, you should set `MEDIA_URL` and `MEDIA_ROOT` in settings.py.

```python
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
```

In production, I usually server static files (static & media folders) with nginx and redirect everything else to my gunicorn server with nginx as a reverse proxy.

**Comment by Boogymanx** [comment]
I have set up my production like that now but haven't deployed the modified code yet as I'm still getting an error locally - here is the traceback, settings and urls.py: https://dpaste.de/qAG4 
The weird thing is that I can still see them uploaded to my /media/spirit/ locally so I know that functionality works, it's just viewing them that doesn't.

**Comment by Boogymanx** [comment]
I've also been trying to implement receiving the signals with no luck so far :/ Here is the relevant code. I know that part of the issue is that I'll also need to subscribe a user to the event key have added when they create a topic, but I'm unsure on how to subscribe them to only one. I'll have to ask the guys that work on django-nyt for more help on that one, I think.

**Comment by nitely** [comment]
> I have set up my production like that now but haven't deployed the modified code yet as I'm still getting an error locally

The static function signature is `static(prefix, view='django.views.static.serve', **kwargs)`, so you are passing `settings.MEDIA_ROOT` as `view`, you should pass it as `document_root` instead.

```python
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```
> I've also been trying to implement receiving the signals with no luck so far :/ Here is the relevant code

You forgot to attach the link. :smile:

**Comment by Boogymanx** [comment]
So I did haha, my bad :p https://dpaste.de/Cr4p is the code. Thanks for your quick reply!

**Comment by nitely** [comment]
Oh, you are attaching the receiver to the handler instead of the signal.

Signals (according to `/signals/handlers/topic_notification.py`) are:
```
comment_posted
topic_private_post_create
topic_private_access_pre_create
topic_viewed   # I think you won't need this one.
```

You can check every *handler* signature to know what arguments you will receive.

So your code should be something like:
```python
@receiver(comment_posted)
def send_comment_notification(sender, comment, **kwargs):
    subscriptors = TopicNotification.objects.filter(topic=comment.topic, is_active=True)\
        .exclude(user=comment.user)\
        values_list('user_id', flat=True)  # or it is just 'user'? I don't remember.

    # Subscribe comment.user (the user who posted the comment)... but I don't know how.

    notify("Somebody replied!", 'comment_posted', target_object=comment.topic, url=comment.get_absolute_url(), recipient_users=subscriptors)
```

I think this won't work since [recipient_users](https://github.com/benjaoming/django-nyt/blob/master/django_nyt/utils.py#L29) should be subscribed to the event first. I've no clue how to do that.

In Spirit, notifications are created whenever an user comment on a topic, or explicitly create it by clicking the "notify me" button. I think, you should create it by connecting (ie: `@receiver(post_save, sender=Notification)`) to the post_save Notification model signal.

There are also *mentions* (ie: `@someuser`), but you broke that by removing *unique* usernames. So, you should not allow notifications at all.

You can disallow mentions like this:
```
#settings.py

ST_MENTIONS_PER_COMMENT = 0
```

**Comment by Boogymanx** [comment]
I managed to get the notifications working - sort of. The problem I currently have is that each user gets a notification as soon as somebody creates a topic or replies. https://dpaste.de/2dj3 is my current receiver. I know that this is because I subscribe my user to comment_posted on creation. I'm guessing the solution to this would be to create an individual EVENT_KEY per topic made, but this seems rather inefficient and I was wondering if you knew a better solution.

**Comment by nitely** [comment]
This should fix it:

```
@receiver(comment_posted)
def send_comment_notification(sender, comment, **kwargs):
    subscriptors = TopicNotification.objects.filter(topic=comment.topic, is_active=True)\
        .exclude(user=comment.user)\
        .values_list('user_id', flat=True)  # or it is just 'user'? I don't remember.

    if subscriptors:
        notify("Somebody replied!", 'comment_posted', target_object=comment.topic, url=comment.get_absolute_url(), recipient_users=subscriptors)
```

**Comment by nitely** [comment]
>  I'm guessing the solution to this would be to create an individual EVENT_KEY per topic made, but this seems rather inefficient and I was wondering if you knew a better solution.

I don't know how django-nyt works and I don't have the time to read the code. You should try the previous solution (check if there are 'subscriptors'), that may work.

If it turns out users get a single/unique 'comment_posted' notification (whether there are many topics with new replies or just one), meaning `target_object` does nothing, you'll probably have to create an event_key per topic. You will do that on `Notification` post save.

**Comment by Boogymanx** [comment]
Yup, that worked! I want to thank you again for your great support, you've been absolutely amazing - going far beyond what I expected. I'm going to try replacing the _header now (which shouldn't bring issues I can't solve myself) so you can close this topic if you want. :)

**Comment by nitely** [comment]
No problem! :smiley: 

I will leave this open for a while.

**Comment by Boogymanx** [comment]
There is actually a slight issue when extending the _header.html. Our header usually starts completely at the left, but gets pushed to the right when including your styles.css. When I try repositioning it with position: absolute, it gets kinda messed up :p is there another template for the content I can maybe extend?

**Comment by nitely** [comment]
How are you including your `style.css`?

To include your `style.css`, I think you should override the `/templates/spirit/_base.html` (copy & paste the entire content into your own `/templates/spirit/_base.html`), currently there is no way to include a custom css (that I know off) without doing this.

The custom `style.css` should only contain the header style, you should add specific selectors (ie: `.myheader .class1 {...}`, `.myheader .class2 {...}`, etc) it'll be the best way, so you don't mess the Spirit styles.

Remember to add:

```python
# settings.py

TEMPLATE_DIRS = [os.path.join(BASE_DIR, 'templates')]
```

So you can place `/templates/spirit/somefile.html` at your root dir (the same containing the media dir) and override whatever template file you need.

**Comment by nitely** [comment]
As of v0.4, Spirit no longer has a custom user model, it extends the django's user model the regular way (OneToOneField), making it much easier to swap the auth system (login, registration, etc).

Before closing this I'd like to:
* Add a *template context processor* to access some of the settings such as `LOGIN_URL` which should be used instead of `spirit:user:auth:login` within templates.
* CSS namespacing `.spirit { @import 'style'; }`, making it easier to add a custom nav-bar or footer (ie: with bootstrap).
* Add a note about adding a `@property def username(): return self.get_full_name()` when implementing a custom user model with no username field, and turning off mentions `ST_MENTIONS_PER_COMMENT = 0`.
* Add a cp admin field to add custom CSS.
