### ISSUE TITLE
Error sending e-mail after registration

### ISSUE THREAD

**Issue by t0rrant** [nitely/Spirit#46]
Hi there,

I'm getting this error

`No handlers could be found for logger "spirit.utils.user.email"`

on apache's log, after completing a registration.

I've configured the e-mail settings, are there any other dependencies?

I'm using an external e-mail provider, by the way.

Thanks in advance

**Comment by t0rrant** [comment]
After adding in the email.py file, before `import logging`

`logging.basicConfig()` 

I now get the following error detail:

`ERROR:spirit.utils.user.email:(-1, 'Dovecot ready.')`
I

**Comment by t0rrant** [comment]
Nevermind... it seems it was a server-side issue.

Cheers and thanks for this great app ;-)

**Comment by nitely** [comment]
Hi!

This was an actual bug. Prior to this fix there was no way to know what was wrong with the email backend.

Thank you!
