### ISSUE TITLE
django 1.8+ support

### ISSUE THREAD

**Issue by auvipy** [nitely/Spirit#47]

**Comment by nitely** [comment]
I'm [working on this](https://github.com/nitely/Spirit/tree/experimental).

**Comment by auvipy** [comment]
thats great!

**Comment by auvipy** [comment]
is it merged?

**Comment by nitely** [comment]
No, it's not. It'll get merge in a month or two.

**Comment by auvipy** [comment]
may I know how much work remain? I'm planning to use that in a project. is there anything that could speed up things? can you point?

**Comment by nitely** [comment]
It's done. You can clone that branch and start using it.

**Comment by auvipy** [comment]
available on pyPI?

**Comment by nitely** [comment]
Nop, you'll have to wait until it's released. For more info, read my last comment  [here](https://github.com/nitely/Spirit/pull/52).

**Comment by nitely** [comment]
Spirit v0.4 is out, it's available on pypi and It supports Django 1.8 :smile: 

Closing this.
