### ISSUE TITLE
Gravatars  should work through the HTTPS if site works through the HTTPS as well

### ISSUE THREAD

**Issue by oduvan** [nitely/Spirit#49]
When I use Spirit on site with https browser shows me an alert that avatars have been loaded from http

**Comment by nitely** [comment]
Any reason why it should not *always* use http**s**?

**Comment by oduvan** [comment]
Actually agree . it should always HTTPS. Right now it is always HTTP

**Comment by oduvan** [comment]
thanks

**Comment by oduvan** [comment]
You did a fix into experimental branch. Not it master? 

Which branch should I use on production?

**Comment by nitely** [comment]
You should use the master branch. The experimental branch will get merge at some point.
