### ISSUE TITLE
Update info on django packages and additional details

### ISSUE THREAD

**Issue by hnykda** [nitely/Spirit#51]
Hello,

thank you for this great piece of software! I've just implemented and wrote a [guide](http://www.danielhnyk.cz/blog/view/installing-spirit-forum-your-website-mandrill).

Anyway, I'm writing that it might be helpful to update [djangopackages](https://www.djangopackages.com/grids/g/forums/) about ability to handle polls and comments in Spirit.

By the way - is there a reason why you test only with Pillow<2.7 or so? I'm happily using spirit with Pillow 2.8.1 withou problems. I'm also using it with Django 1.8.1 (I used the experimental branch).

Additionally, no documentation at all can be found about spirit. Not even for users of spirit. Some **help** button on the site would be appreciated. There users could learn about markdown, emoticons, avatars, private topics etc. 

Even I, as a developer, don't know what are the possibilities of this forum. For example I wanted to insert google analytics code to `_footer.html`, but I wasn't able to override the default one from virtualenv...

Thank you

**Comment by nitely** [comment]
> By the way - is there a reason why you test only with Pillow<2.7 or so? I'm happily using spirit with Pillow 2.8.1 withou problems. I'm also using it with Django 1.8.1 (I used the experimental branch).

Not, really. If tests passes, then it's ok. I will update dependencies before merging that branch into master.

> Additionally, no documentation at all can be found about spirit.

That's right, there is none. I thinking in start writting some of it, to show how to install Spirit and how to integrate to existing sites/platforms (ie: mezzanine, etc).

> Not even for users of spirit. Some help button on the site would be appreciated. There users could learn about markdown, emoticons, avatars, private topics etc.

As an user, I'd not read it. If something is not immediately obvious then it's an UX issue. There should be links to docs (a popup?) in appropriate places for *implicit/hidden* features such as emojis and mentions (ie: in the comment box).

> For example I wanted to insert google analytics code to _footer.html, but I wasn't able to override the default one from virtualenv...

For that specific case, there is a text box in the admin panel to insert code. The template system is more related to django than to Spirit. I get your point, though.

**Comment by kotrfa** [comment]
You are right - I should have run tests first. Sorry for that.

It's nice to hear about docs and you are right about the second part about user docs too. The popups sounds nice and not disturbing. 

And I unfortunately can't find the text box where the code should be inserted.

Didn't know about the details with descriptions.

Ok, thank you for the answers and great work!
