### ISSUE TITLE
make spirit django app or work better with existing django project

### ISSUE THREAD

**Issue by auvipy** [nitely/Spirit#55]

**Comment by auvipy** [comment]
you could add a local settings module which can be adjusted/overwritten in django settings

**Comment by nitely** [comment]
what do you mean by this?

**Comment by nitely** [comment]
Oh, I know what you mean. A *local_settings.py* file, right?

ie:

```python
# ...

try:
    from local_settings.py import *
except ImportError:
    pass
```

I used to do that. The new approach I've taken is so much better, it allows you not only to override setting but also to extend them (lists variables, dicts, tuples, etc).

You can import the `spirit.settings` as shown in the [base.py](https://github.com/nitely/Spirit/blob/master/example/project/settings/base.py) example or even import the `base` itself. You can import/extend any of the other [settings](https://github.com/nitely/Spirit/tree/master/example/project/settings) files.

ie:


```python
# local.py
from .prod import *

SECRET_KEY = os.environ.get("SECRET_KEY", "")
ALLOWED_HOSTS = ['.example.com', ]
ADMINS = (('John', 'john@example.com'), )

# Extending apps (notice the plus sign)
INSTALLED_APPS += (
    # 'my_app1',
)

# ... etc
```

Then set your environment settings module:

```python
# manage.py

# ...
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "project.settings.local")
```

Or passing it as a parameter when running the server (ie: gunicorn) `$ python manage.py runserver --settings=project.settings.local`

You should read the [example](https://github.com/nitely/Spirit/tree/master/example) code, there's everything you need in there.

**Comment by auvipy** [comment]
https://github.com/alexhayes/django-google-adwords/tree/master/django_google_adwords how about the aooroach followed?

**Comment by nitely** [comment]
It seems to use an app called [django-appconf](http://django-appconf.readthedocs.org/en/latest/) to set the config. Spirit comes with a lot pre configured django settings and other third party apps, I don't see how that package can help us there.

**Comment by auvipy** [comment]
ohh!! thats coool!!!
