### ISSUE TITLE
What is the best way to add GA?

### ISSUE THREAD

**Issue by oduvan** [nitely/Spirit#56]
Do you have a best practice for adding a Google Analytics code on the site?

It should be placed right after <body> tag.

Thanks

**Comment by nitely** [comment]
I'd say put it in the footer (`admin -> basic configuration -> footer snippet`).

According to Google, it's best to put it before the closing head tag `</head>`, so you make sure it'll load before the visitor leaves the page, but that will also slow down your initial/first page load.

it'll count the visit one way or the other (header or footer won't make any major difference), but the slow down when it's placed within the header is real.

You can read [this](http://stackoverflow.com/questions/3173571/should-i-put-the-google-analytics-js-in-the-head-or-at-the-end-of-body) stackoverflow Q&A and make your own mind :smile:

**Comment by oduvan** [comment]
It is all understandable  but if I want to follow googles instructions there is not true way to do so. Am I correct?

**Comment by boulderdave** [comment]
If you do not have it before the closing </head>, then I don't believe you will be able to verify you own the domain for other services like Webmaster tools, if you choose to do so via Google Analytics. 

It will only look in the <head> for the code for verification.
