### ISSUE TITLE
"Too many submissions, wait 10s." shows up right after I do form submit correction

### ISSUE THREAD

**Issue by oduvan** [nitely/Spirit#58]
Work flow

1. Open forum creation form
2. Put title and subject
3. Submit
4. Get an error, I forgot to choose a category
5. Choose category. Submit
6. "Too many submissions, wait 10s."
7. Puzzled

**Comment by nitely** [comment]
That's the current behaviour, what's your suggestion?

**Comment by oduvan** [comment]
"Too many submissions" is what user want to make 10 submissions in 10s

**Comment by alesdotio** [comment]
1/10s is sometimes a bit annoying, because if you make a mistake in the form you have to wait 10s to try again. How about adding a setting for the ratelimit @nitely?

**Comment by nitely** [comment]
It's very annoying actually :smile: .

@alesdotio What kind of setting?

1 post (notice I did *not* say submission) every 10 seconds is probably ok. The ratelimit should be increase only when the form does not contain errors.

**Comment by alesdotio** [comment]
Yeah, preventing double posting is also a good idea. For most cases you can do this on the frontend, but I see how doing it this way is cleaner. As you said, the ratelimit not applying when there is a form error would be the best solution here. In any case, I think adding the settings would still be nice for people that dislike the defaults.

**Comment by nitely** [comment]
> In any case, I think adding the settings would still be nice for people that dislike the defaults.

I'm afraid this is the start of a very customizable forum software... and when you less expect it, we have another [insert one of the many legacy forums here].

IMHO, final users should not have to care about this kind of stuff, the software should *just work*.

**Comment by alesdotio** [comment]
I completely agree, the forum user should not care at all about this and should not fight the software. Developers, however, more often then not, need customization and providing **optional** settings for this kind of stuff is a good idea. Having sensible defaults also goes a long way.

**Comment by henri-hulski** [comment]
In my opinion, preventing reposting is enough. 
No need for customization here.

**Comment by Xeniac-at** [comment]
IMHO the current workflow is not that great. @oduvan got a "Too many submissions" message, but he submitted nothing. He tried to submit an invalid form, got an rejection and fixed the error(s) within 10 seconds. 

It should be sufficient when the 10 seconds countdown starts after an successful submission. To prevent doubleposts and spammers, but it's a bad idea to punish people who fix their mistakes in 10 seconds.

**Comment by nitely** [comment]
Since #118 fixes the double post issue, this can be fixed. I'm working on it at `feature/rate_limit_on_valid_post_only_58` branch.
