### ISSUE TITLE
Adding Spirit to Existing Project With Django User Model

### ISSUE THREAD

**Issue by badisa** [nitely/Spirit#59]
Hi,

I am interested in implementing this app into my project, but I am using the Django user model. Which your README said to use https://github.com/nitely/Spirit-User-Profile for, however that is deprecated. So I was wondering what my course of action should be.

Thanks.

**Comment by nitely** [comment]
Hello!

Spirit 0.3 will drop the custom user model in favor of a regular profile
model (oneToOneField).

It will be released this week. The current development is taking place in
the experimental branch, you can checkout that branch and try to integrate
it to your project in the meantime.

**Comment by hyusetiawan** [comment]
@nitely would love to know the status of this, I am in the process of reviewing several forums, so far Spirit is the favored solution but it needs to integrate to django user admin which uses default django user model

**Comment by nitely** [comment]
@hyusetiawan It's about to be released, tomorrow probably. Spirit 0.4 will be released soon after, maybe even the same day, since 0.3 is just a bridge between the old project structure and the new one.

Spirit 0.3 will drop the custom user model, as stated above.

**Comment by nitely** [comment]
Spirit v0.4 is out, and this has been mitigated, it drops the custom user model in favor of the regular Django user model.

Closing this.
