### ISSUE TITLE
RelatedObjectDoesNotExist while integrating Spirit to existing project: "User has no st."

### ISSUE THREAD

**Issue by CheapSeth** [nitely/Spirit#62]
Hi!
I'm trying to add the latest version of spirit to an existing project. I installed the dependencies and all, but when I run the server, I get a «RelatedObjectDoesNotExist» - User has no st on every page.

It appears that it is because I already have users in my database, so I'm going to add them a placeholder UserProfile via the manage.py shell…

But is there a more efficient/recommended/documented way to do it?

**Comment by nitely** [comment]
Hello!

Dang it! I knew I was forgetting something... :sweat_smile: 
I'll create a new data migration to populate the UserProfile ASAP.

**Comment by nitely** [comment]
All done!

**Comment by CheapSeth** [comment]
Thank you very much :)

And congratulations for the work you've done on Spirit, it's so far the best forum software I've used on my projects.
