### ISSUE TITLE
Relation "spirit_topic" does not exist on freshly installed spirit 0.4.1

### ISSUE THREAD

**Issue by ngaurav** [nitely/Spirit#64]
Actually "spirit_topic_topic" table is present in the db. But I am unable to understand why django is querying "spirit_topic"
<img width="1194" alt="screen shot 2015-08-02 at 7 36 18 pm" src="https://cloud.githubusercontent.com/assets/12483343/9026465/dc6e9ef8-394d-11e5-9c27-48b6f2bcf9be.png">

**Comment by ngaurav** [comment]
This is the error:

relation "spirit_topic" does not exist
LINE 1: ...*') FROM (SELECT "spirit_topic"."id" AS Col1 FROM "spirit_to...
                                                             ^

**Comment by nitely** [comment]
Can you paste the full traceback?

**Comment by ngaurav** [comment]
Sorry It required me to restart nginx. That fixed the problem.

**Comment by nitely** [comment]
Great!

Closing this.
