### ISSUE TITLE
Poll is not working properly

### ISSUE THREAD

**Issue by Macbull** [nitely/Spirit#65]
I don't see any way to add more than 2 options.

**Comment by Macbull** [comment]
@nitely Is there any version of repo, in which poll was working perfectly. It does not seem to have option for adding more than 2 choices. Nor does it show result anywhere !

**Comment by nitely** [comment]
No, there is not. I realized that's not the way I want polls to work and didn't manage to finish it.
I'll try to get what I want (markdown polls inside comments) this weekend.

**Comment by Macbull** [comment]
@nitely  great ! One more question, Is master branch stable enough, or should I stick to 0.4.x ?

**Comment by nitely** [comment]
You should stick to 0.4.x.

Master is the active dev branch. Sometimes there will be backward incompatible changes, when that happens I increase the major version (actually the minor until Spirit reaches v1, at least).

**Comment by Macbull** [comment]
@nitely : whats the status of branch markdown_poll ? Is the poll in that branch ready to use ?

**Comment by nitely** [comment]
> whats the status of branch markdown_poll ?

WIP.

> Is the poll in that branch ready to use ?

None of the `feature/...` are.

I'm close to get it done, though. I'll merge it to `master` as soon as it's ready.
