### ISSUE TITLE
Extending RegistrationForm

### ISSUE THREAD

**Issue by solvents** [nitely/Spirit#72]
I wanted to extend RegistrationForm to include a captcha field. What I ended up needing to do was to copy the `register` view and change the `RegistrationForm` class used to a custom form.

I think it would be better if you could specify the `RegistrationForm` class as an optional argument to `register`. Then you would only need to define your custom form and add a url entry that passed the extra argument.

Alternatively, if there is already an easy way to do this, maybe you could add an example?
Thanks!

**Comment by nitely** [comment]
> I think it would be better if you could specify the RegistrationForm class as an optional argument to register. Then you would only need to define your custom form and add a url entry that passed the extra argument.

Yes, that's the canonical way in Django. I'll try to get in done ASAP.

> Alternatively, if there is already an easy way to do this, maybe you could add an example?

No, there is not... but [there will be](https://github.com/nitely/django-hooks) soon.
