### ISSUE TITLE
ImportError: No module named 'spirit'

### ISSUE THREAD

**Issue by gogobook** [nitely/Spirit#73]
I got 'spirit' by 'git clone', and then follow instructions in README.md. Then I got this error. I know this about 'PYTHONPATH'. And I got the solution by make an soft link in PYTHONPATH. So I think it maybe a document issue.

**Comment by nitely** [comment]
> I got 'spirit' by 'git clone', and then follow instructions in README.md.

I'm guessing the main `README.md`, you should follow the [example readme](https://github.com/nitely/Spirit/tree/master/example)

> So I think it maybe a document issue.

Yes, the `pip install -r requirements.txt` step should be `pip install spirit`, no cloning required. I'll fix it ASAP.

> And I got the solution by make an soft link in PYTHONPATH

This is [how modules get imported twice](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-double-import-trap) and weird bugs happens.

**Comment by gogobook** [comment]
Thank you @nitely. But installed by `pip install django-spirit` won't have "example" directory. After 'pip install django-spirit', shoud I use 'django-admin startproject mysite' to start project? And what I need to do to run 'python manage.py spiritinstall'? Sorry, that's a lot questions to bother you.

**Comment by nitely** [comment]
Following the example readme should work for you.

The main readme steps are to integrate Spirit in to a existing project. The
above solution is shorter than starting a django project, etc but both
should work the same.

**Comment by gogobook** [comment]
I found the 'example' directory in site-packages when installed spirit by 'pip install django-spirit'. I thought 'example' maybe need to change to another name, like 'django-spirit-example'. And there is no 'manage.py' in the 'example'. How I need to do is better? Copy it from other place?

**Comment by nitely** [comment]
> I found the 'example' directory in site-packages when installed spirit by 'pip install django-spirit'

That happens when you install via `pip install .`

> And there is no 'manage.py' in the 'example'. How I need to do is better? Copy it from other place?

Ignore that folder. Go to: https://github.com/nitely/Spirit/tree/master/example and follow the instructions to the letter.
