### ISSUE TITLE
Error: Cannot create form field for 'category' yet (Windows)

### ISSUE THREAD

**Issue by harish211** [nitely/Spirit#74]
Thank you for this open source forum.Really helpful 

I've trying to install it using the readme on the front page, through pip, cloned it, used the example, also tried this https://github.com/nitely/Spirit/issues/73.

These seems to be some errors while `python manage.py runserver`. I'm using windows and django==1.8.

This is one of the error I keep getting:

`Cannot create form field for 'category' yet, because its related model u'spirit_category.Category' has not been loaded yet`

I got stuck here for days.So,if you could please take time to explain the step-wise installation procedure, it would be helpful to me. 
I appreciate that.
Thank you so much.

**Comment by nitely** [comment]
Follow [these instructions](https://github.com/nitely/Spirit/tree/master/example#running-the-example-application), I just tried them, they work.

If it does not work for you, since I'm not a Windows user, I can't help you further.

**Comment by nitely** [comment]
I found someone raised a similar question at the spirit community [0]. The instructions linked above seem to have solve the issue. The user who asked this was running Windows, btw.

[0] http://community.spirit-project.com/topic/217/installation-problems-python-newbie/

**Comment by Nirmalatatikonda** [comment]
Harish - were you able to get this resolved. I am running into the same issue when integrating spirit into an existing django website on windows.

Thanks!!

**Comment by nitely** [comment]
Did you tried running the [https://github.com/nitely/Spirit/tree/master/example#running-the-example-application](example project)?

**Comment by nitely** [comment]
I found what's going on. You are *overriding* the `INSTALLED_APP` instead of [extending it](https://github.com/nitely/Spirit/blob/v0.4.x/example/project/settings/base.py#L24).

I suggest you take the `example.settings.base.py` and modified accordingly for your (existing) project.

**Comment by Nirmalatatikonda** [comment]
Thanks for the inputs, that was helpful. I am moving in the right direction but now I have run into another problem.

I am trying to integrate spirit into an existing mezzanine app which also has "mezzanine.core" app in settings.py. Spirit/settings.py has "spirit.core". So now i am getting the following error:

django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: core

Any ideas on how to resolve this duplicate issue.

**Comment by nitely** [comment]
You should open a new issue.
