### ISSUE TITLE
Integration into Another App

### ISSUE THREAD

**Issue by timolson** [nitely/Spirit#75]
We are trying to integrate Spirit into a larger website to not only add a separate forum section, but to also put comments at the bottom of several pages.  The big problem is embedding the topic detail, along with the comment edit box, into one of our own pages.  All the templates and URLs and views seem to assume that Spirit owns the top-level page, POSTing to a Spirit URL which is unaware that we need a different page rendered after the submission.  The only way I currently see is to copy all the Spirit views we need, modify them to include the additional context information we need for each page, then override the template.  That's a lot of code copying and/or a hard fork of Spirit.

Any ideas on a better way this could be done?  Or is Spirit just meant to be a standalone app only?

**Comment by nitely** [comment]
Spirit is meant to be a standalone app. That said, you may get away with what you want without too many changes:

Every view will redirect to a input called *next* after POSTing:

```html
# template.html
# context = {'next': '/blog/article/1/', ...}
{% load spirit_tags %}
{% render_comments_form topic=article.topic %}
```
You would create a dummy topic when creating an article and possibly a dummy comment with a link pointing to the blog article.

Rendering the comment list is trickier, there are a few options:

* You could copy&paste the `topic.detail` view and most of the detail template in to your article view.
* You could create a templatetag that renders the comment list, again, copy&pasting most of the topic.detail code.
* You could create a view that returns *a simpler* comment list as an AJAX response, return just the first ten results and add a "read more" button that redirects to the dummy topic or may be add a infinite pagination.

The latter (AJAX response) I may merge it in to the Spirit project since it's what I'll probably do at some point. I won't merge the second option, coz it's only good for django projects.

**Comment by timolson** [comment]
Thanks for the helpful feedback.  What if I made a slight modification to Spirit to separate the `render` calls from the context creation, for example like this:

```
def get_publish_context(request,category_id):
# … set up the forms etc …
    context = {
        'form': form,
        'cform': cform,
        'pform': pform,
        'pformset': pformset
    }
    return context

@login_required
@ratelimit(rate='1/10s')
def publish(request, category_id=None):
    return render(request, 'spirit/topic/publish.html', get_publish_context(request,category_id))
```

If this is the case, then our views can combine the context we need with the context Spirit needs:
```
def my_custom_view(request,category_id,other_arg):
    context = get_publish_context(request,category_id)
    context['foo'] = get_bar(other_arg)
    return render(request,'myapp/page_with_topics.html',context)
```

This allows us to reuse the spirit view code without copying it.  What do you think about this, and would you accept a PR with this refactoring?

**Comment by nitely** [comment]
That should work. But no, I would not accept such PR. Sadly, I have
sacrificed extensibility for simplicity. Any PR that decreases simplicity
in the name of extensibility will be rejected. I would have used CBV
otherwise, but I know it is not possible to support every user case under
the sun, so I won't even try it.

2015-10-02 15:31 GMT-03:00 Tim Olson <notifications@github.com>:

**Comment by timolson** [comment]
Actually, `context = {'next': '/blog/article/1/', ...}` does not seem to work for the topic detail page, nor does adding `?next=…` to the query string.  The form posts always go to the original Spirit page, not the page listed as `next`.  Is this a bug?  All the URLs on the page seem to be generated with the `{% url 'spirit:…' %}` template tag, which wouldn't add `next` to the query string unless you made some hack?

**Comment by nitely** [comment]
It seems you have to add *next* as a parameter to the templatetag `{% render_comments_form topic=article.topic next=article.get_absolute_url %}`.

I've taken a second look and most of the views will do something like this: `redirect(request.POST.get('next', obj.get_absolute_url()))`, I thought they were doing: `redirect(request.POST.get('next', request.GET.get('next', obj.get_absolute_url())))`

**Comment by timolson** [comment]
Thanks for your comments.  I still couldn't get the `next` parameter to work, but we've taken a different approach.  For those interested:

I replaced `django.shortcuts.render` with a wrapper method.  When a certain flag is set, the wrapper method returns the `context` passed to `render` instead of the resulting HTML.  I then use this flag in a method called `get_view_context()` used like this:

```python
def get_view_context(view_func,*args,**kwargs):
	global _rendering_enabled
	_return_context_instead_of_rendering = True
	# the special render() wrapper, and therefore the view function, will return the context instead of the rendered template
	context = view_func(*args,**kwargs)
	_return_context_instead_of_rendering = False
	return context
```

```python
@register.inclusion_tag('my_app/my_topic_snippet.html', takes_context=True, name='topic')
def topic_tag(context, topic):
	request = context['request']
	context = get_view_context(spirit.topic.views.detail, request, topic.id, topic.slug)
	context['request'] = request
	context['my_var'] = get_var()
	return context
```

Then, `my_app/my_topic_snippet.html` can include or otherwise copy template code from Spirit and have the correct context available.  No changes were made to Spirit to accomplish this, so it should be more maintainable.  We then just drop Spirit components into our own templates using `{% topic my_topic_obj %}`

Anyone interested can PM me for more details.

**Comment by nitely** [comment]
> I replaced django.shortcuts.render with a wrapper method. When a certain flag is set, the wrapper method returns the context passed to render instead of the resulting HTML.

Is that thread-safe? When that flag is set, any request to the original view while return the context instead of the renderer HTML, unless you have made it thread safe somehow.

**Comment by timolson** [comment]
Oh, I assumed Django was single-threaded.  The fix is easy
```python
# executed by __init__.py
from functools import wraps

import django
from django.shortcuts import render
from django.template.engine import _context_instance_undefined, _dictionary_undefined, _dirs_undefined
from django.template.context import _current_app_undefined
import threading


def get_view_context(view_func,*args,**kwargs):
	_return_context_instead_of_rendering.value = True
	context = view_func(*args,**kwargs)
	_return_context_instead_of_rendering.value = False
	return context


# this method replaces the standard django.shortcuts.render(...)
@wraps(django.shortcuts.render)
def _render_wrapper(request, template_name, context=None,
              context_instance=_context_instance_undefined,
              content_type=None, status=None, current_app=_current_app_undefined,
              dirs=_dirs_undefined, dictionary=_dictionary_undefined,
              using=None):
	if getattr(_return_context_instead_of_rendering,'value',False):
		return context
	else:
		return _django_render(request, template_name, context, context_instance, content_type,
	                                        status, current_app, dirs, dictionary, using)


_return_context_instead_of_rendering = threading.local()
_django_render = django.shortcuts.render
django.shortcuts.render = _render_wrapper
```

This code must be called from `__init__.py` so that it redefines the `render()` method before the Spirit app is loaded.
