### ISSUE TITLE
type object 'BlockLexer' has no attribute 'default_features'

### ISSUE THREAD

**Issue by Anchondo** [nitely/Spirit#77]
AttributeError at /topic
type object 'BlockLexer' has no attribute 'default_features'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/topic
Django Version:	1.8
Exception Type:	AttributeError
Exception Value:	
type object 'BlockLexer' has no attribute 'default_features'
Exception Location:	C:\Python27\lib\site-packages\spirit\core\utils\markdown\block.py in BlockLexer, line 97
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.8
Python Path:	
['C:\\Users\\Robert\\Desktop\\forum\\forum',
 'C:\\Python27\\lib\\site-packages\\xlrd-0.9.3-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\pip-1.5.6-py2.7.egg',
 'C:\\Python27\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages']
Server time:	Sat, 17 Oct 2015 15:51:59 +0000

That is the issue that i am getting when i am using this app with my production enviorment any ideas why?

**Comment by nitely** [comment]
Spirit requires mistune==0.3, It seems you installed the wrong version. Try
running `$ pip show mistune`, it should display `version: 0.3.1` to work.

Ps. I'll update that dependencie later, thanks for the reminder.

**Comment by Anchondo** [comment]
does not allow me to download the 0.3 only the newer version


________________________________

**Comment by nitely** [comment]
`$ pip install mistune==0.3.1` will install that specific version. Following the [installation guide](https://github.com/nitely/Spirit/tree/master/example) will install the right version for every dependency, I don't know why you have a different one.
