### ISSUE TITLE
topic private publish in example

### ISSUE THREAD

**Issue by Thrills** [nitely/Spirit#78]
If i try send a private message to another user i get a "category matching query does not exist"
![error](https://cloud.githubusercontent.com/assets/8602048/10563713/74c9175e-7595-11e5-8de5-81ab9be9b54b.PNG)

**Comment by nitely** [comment]
Did you runned `$ python manage.py spiritinstall` for your current database?

**Comment by nitely** [comment]
Closing this. Feel free to re-open it.
