### ISSUE TITLE
Having trouble adding django-spirit to an exisiting mezzanine website

### ISSUE THREAD

**Issue by Nirmalatatikonda** [nitely/Spirit#79]
I am tying to integrate django-spirit into an existing mezzanine website on windows.

I followed the following instructions:
https://github.com/nitely/Spirit/blob/master/README.md

When i launch the website now I get the following error:

Exception Value:	
Cannot create form field for 'category' yet, because its related model u'spirit_category.Category' has not been loaded yet

Any ideas on how to get this resolved and move forward with the integration. Appreciate the inputs.

Thanks,
Nirmala

**Comment by nitely** [comment]
Duplicated #74
