### ISSUE TITLE
Duplicate "core" issue when integrating spirit into existing mezzanine website

### ISSUE THREAD

**Issue by Nirmalatatikonda** [nitely/Spirit#80]
I am trying to integrate spirit into an existing mezzanine app which also has "mezzanine.core" app in settings.py. Spirit/settings.py has "spirit.core". So I am getting the following error:

django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: core

Any ideas on how to resolve this duplicate issue.

Thanks!!

**Comment by nitely** [comment]
I'll release the patched version in the next few days. You can clone the master repo if you don't want to wait.

Thanks for reporting this one.

**Comment by Nirmalatatikonda** [comment]
Thanks for the prompt resolution.
