### ISSUE TITLE
Customizing the spirit user interface

### ISSUE THREAD

**Issue by Nirmalatatikonda** [nitely/Spirit#82]
Is there a way to customize the Spirit User interface (Apply different styles) if i am not including the source code in my project.

Thanks,
Nirmala

**Comment by nitely** [comment]
Yes, you can override the templates, just like any other Django app.

**Comment by nitely** [comment]
CLosing this. Feel free to re-open it.

**Comment by grwhumphries** [comment]
Hi @nitely -> any suggested documentation on how to do this exactly? I've been trying to go about doing this, but haven't had any luck.  Would be a handy thing to have in your documentation on how to integrate nicely with an existing page. Or maybe a blog post on how to do it.
