### ISSUE TITLE
Admin page is not loading after adding spirit to an existing mezzanine website

### ISSUE THREAD

**Issue by Nirmalatatikonda** [nitely/Spirit#83]
I added spirit to an existing mezzanine website and all features of spirit seem to work fine now. But I am getting the following exception when loading the sites admin page. Any help in getting this resolved will be appreciated. Thanks!!

Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/
Django Version:	1.8.4
Exception Type:	VariableDoesNotExist
Exception Value:	
Failed lookup for key [settings] in u"[{'False': False, 'None': None, 'True': True}, {}, {}, {'site_header': <django.utils.functional.__proxy__ object at 0x02EAEF10>, 'site_title': <django.utils.functional.__proxy__ object at 0x02EAEEF0>, 'title': <django.utils.functional.__proxy__ object at 0x02EAEFB0>, 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x03E4CE10>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x0389B0F0>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x02EB8A90>, 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/blog/blogcategory/', 'object_name': 'BlogCategory', 'name': <django.utils.functional.__proxy__ object at 0x03E4CA30>, 'add_url': u'/admin/blog/blogcategory/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/blog/blogpost/', 'object_name': 'BlogPost', 'name': <django.utils.functional.__proxy__ object at 0x03E4CCD0>, 'add_url': u'/admin/blog/blogpost/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}, {'app_url': u'/admin/conf/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/conf/setting/', 'object_name': 'Setting', 'name': <django.utils.functional.__proxy__ object at 0x03E4CD50>, 'add_url': u'/admin/conf/setting/add/'}], 'has_module_perms': True, 'name': u'Conf', 'app_label': u'conf'}, {'app_url': u'/admin/forms/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/forms/form/', 'object_name': 'Form', 'name': <django.utils.functional.__proxy__ object at 0x03E4C310>, 'add_url': u'/admin/forms/form/add/'}], 'has_module_perms': True, 'name': u'Forms', 'app_label': u'forms'}, {'app_url': u'/admin/galleries/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/galleries/gallery/', 'object_name': 'Gallery', 'name': <django.utils.functional.__proxy__ object at 0x03DC70F0>, 'add_url': u'/admin/galleries/gallery/add/'}], 'has_module_perms': True, 'name': u'Galleries', 'app_label': u'galleries'}, {'app_url': u'/admin/generic/', 'models': [{'perms': {'add': False, 'change': True, 'delete': True}, 'admin_url': u'/admin/generic/threadedcomment/', 'object_name': 'ThreadedComment', 'name': <django.utils.functional.__proxy__ object at 0x03E4C4B0>}], 'has_module_perms': True, 'name': u'Generic', 'app_label': u'generic'}, {'app_url': u'/admin/pages/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True},

**Comment by nitely** [comment]
I don't find that exception quite useful. Can you paste the full traceback, including the line that raised the exception? Your settings file would be helpful as well.

**Comment by Nirmalatatikonda** [comment]
Here you go. I have attached a copy of the settings file.

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/

Django Version: 1.8.4
Python Version: 2.7.9
Installed Applications:
[u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.messages',
 u'spirit.core',
 u'spirit.admin',
 u'spirit.search',
 u'spirit.user',
 u'spirit.user.admin',
 u'spirit.user.auth',
 u'spirit.category',
 u'spirit.category.admin',
 u'spirit.topic',
 u'spirit.topic.admin',
 u'spirit.topic.favorite',
 u'spirit.topic.moderate',
 u'spirit.topic.notification',
 u'spirit.topic.poll',
 u'spirit.topic.private',
 u'spirit.topic.unread',
 u'spirit.comment',
 u'spirit.comment.bookmark',
 u'spirit.comment.flag',
 u'spirit.comment.flag.admin',
 u'spirit.comment.history',
 u'spirit.comment.like',
 u'spirit.comment.poll',
 u'djconfig',
 u'haystack',
 u'mainapp',
 u'django.contrib.redirects',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.pages',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.galleries',
 u'mezzanine.twitter',
 u'recipe',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django_comments']
Installed Middleware:
[u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'spirit.user.middleware.TimezoneMiddleware',
 u'spirit.user.middleware.LastIPMiddleware',
 u'spirit.user.middleware.LastSeenMiddleware',
 u'spirit.user.middleware.ActiveUserMiddleware',
 u'spirit.core.middleware.PrivateForumMiddleware',
 u'djconfig.middleware.DjConfigMiddleware',
 u'mezzanine.core.middleware.UpdateCacheMiddleware',
 u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'mezzanine.core.middleware.FetchFromCacheMiddleware']


Template error:
In template C:\Python27\lib\site-packages\grappelli_safe\templates\admin\base.html, error at line 19
   (Could not get exception message)

   9 : 



   10 : 



   11 : {% block stylesheets %}



   12 :     <link rel="stylesheet" type="text/css" href="{% static "grappelli/css/base.css" %}" />



   13 : {% endblock %}



   14 : 



   15 : {% block extrastyle %}{% endblock %}



   16 : 



   17 : 



   18 : {% block javascripts %}



   19 : <script type="text/javascript" src=" {% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %} "></script>



   20 : <script type="text/javascript">



   21 :     // Ensures jQuery does not pollute the global namespace



   22 :     $.noConflict();



   23 :     {% url "admin:index" as admin_index_url %}



   24 :     var ADMIN_URL = "{{ admin_index_url }}";



   25 : </script>



   26 : {% endblock %}



   27 : 



   28 : {% block extrahead %}{% endblock %}



   29 : 


Traceback:
File "C:\Python27\lib\site-packages\django\core\handlers\base.py" in get_response
  164.                 response = response.render()
File "C:\Python27\lib\site-packages\django\template\response.py" in render
  158.             self.content = self.rendered_content
File "C:\Python27\lib\site-packages\django\template\response.py" in rendered_content
  135.         content = template.render(context, self._request)
File "C:\Python27\lib\site-packages\django\template\backends\django.py" in render
  74.         return self.template.render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  209.                     return self._render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in _render
  201.         return self.nodelist.render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  903.                 bit = self.render_node(node, context)
File "C:\Python27\lib\site-packages\django\template\debug.py" in render_node
  79.             return node.render(context)
File "C:\Python27\lib\site-packages\django\template\loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in _render
  201.         return self.nodelist.render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  903.                 bit = self.render_node(node, context)
File "C:\Python27\lib\site-packages\django\template\debug.py" in render_node
  79.             return node.render(context)
File "C:\Python27\lib\site-packages\django\template\loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in _render
  201.         return self.nodelist.render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  903.                 bit = self.render_node(node, context)
File "C:\Python27\lib\site-packages\django\template\debug.py" in render_node
  79.             return node.render(context)
File "C:\Python27\lib\site-packages\django\template\loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in render
  903.                 bit = self.render_node(node, context)
File "C:\Python27\lib\site-packages\django\template\debug.py" in render_node
  79.             return node.render(context)
File "C:\Python27\lib\site-packages\django\templatetags\static.py" in render
  105.         url = self.url(context)
File "C:\Python27\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py" in url
  15.         path = self.path.resolve(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in resolve
  668.                     arg_vals.append(arg.resolve(context))
File "C:\Python27\lib\site-packages\django\template\base.py" in resolve
  787.             value = self._resolve_lookup(context)
File "C:\Python27\lib\site-packages\django\template\base.py" in _resolve_lookup
  839.                                                        (bit, current))  # missing attribute

Exception Type: VariableDoesNotExist at /admin/
Exception Value: Failed lookup for key [settings] in u"[{'False': False, 'None': None, 'True': True}, {}, {}, {'site_header': <django.utils.functional.__proxy__ object at 0x02EAEF10>, 'site_title': <django.utils.functional.__proxy__ object at 0x02EAEEF0>, 'title': <django.utils.functional.__proxy__ object at 0x02EAEFB0>, 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': <django.utils.functional.__proxy__ object at 0x03E4CE10>, 'add_url': u'/admin/auth/group/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': <django.utils.functional.__proxy__ object at 0x0389B0F0>, 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x02EB8A90>, 'app_label': 'auth'}, {'app_url': u'/admin/blog/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/blog/blogcategory/', 'object_name': 'BlogCategory', 'name': <django.utils.functional.__proxy__ object at 0x03E4CA30>, 'add_url': u'/admin/blog/blogcategory/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/blog/blogpost/', 'object_name': 'BlogPost', 'name': <django.utils.functional.__proxy__ object at 0x03E4CCD0>, 'add_url': u'/admin/blog/blogpost/add/'}], 'has_module_perms': True, 'name': u'Blog', 'app_label': u'blog'}, {'app_url': u'/admin/conf/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/conf/setting/', 'object_name': 'Setting', 'name': <django.utils.functional.__proxy__ object at 0x03E4CD50>, 'add_url': u'/admin/conf/setting/add/'}], 'has_module_perms': True, 'name': u'Conf', 'app_label': u'conf'}, {'app_url': u'/admin/forms/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/forms/form/', 'object_name': 'Form', 'name': <django.utils.functional.__proxy__ object at 0x03E4C310>, 'add_url': u'/admin/forms/form/add/'}], 'has_module_perms': True, 'name': u'Forms', 'app_label': u'forms'}, {'app_url': u'/admin/galleries/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/galleries/gallery/', 'object_name': 'Gallery', 'name': <django.utils.functional.__proxy__ object at 0x03DC70F0>, 'add_url': u'/admin/galleries/gallery/add/'}], 'has_module_perms': True, 'name': u'Galleries', 'app_label': u'galleries'}, {'app_url': u'/admin/generic/', 'models': [{'perms': {'add': False, 'change': True, 'delete': True}, 'admin_url': u'/admin/generic/threadedcomment/', 'object_name': 'ThreadedComment', 'name': <django.utils.functional.__proxy__ object at 0x03E4C4B0>}], 'has_module_perms': True, 'name': u'Generic', 'app_label': u'generic'}, {'app_url': u'/admin/pages/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/pages/link/', 'object_name': 'Link', 'name': <django.utils.functional.__proxy__ object at 0x03E4C690>, 'add_url': u'/admin/pages/link/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/pages/page/', 'object_name': 'Page', 'name': <django.utils.functional.__proxy__ object at 0x03DBDFF0>, 'add_url': u'/admin/pages/page/add/'}, {'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/pages/richtextpage/', 'object_name': 'RichTextPage', 'name': <django.utils.functional.__proxy__ object at 0x03E4CF90>, 'add_url': u'/admin/pages/richtextpage/add/'}], 'has_module_perms': True, 'name': u'Pages', 'app_label': u'pages'}, {'app_url': u'/admin/recipe/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/recipe/recipepost/', 'object_name': 'RecipePost', 'name': <django.utils.functional.__proxy__ object at 0x03E4CA50>, 'add_url': u'/admin/recipe/recipepost/add/'}], 'has_module_perms': True, 'name': u'Recipe', 'app_label': u'recipe'}, {'app_url': u'/admin/redirects/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/redirects/redirect/', 'object_name': 'Redirect', 'name': <django.utils.functional.__proxy__ object at 0x03DBDD30>, 'add_url': u'/admin/redirects/redirect/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x02F31D10>, 'app_label': 'redirects'}, {'app_url': u'/admin/sites/', 'models': [{'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': u'/admin/sites/site/', 'object_name': 'Site', 'name': <django.utils.functional.__proxy__ object at 0x03E4CFD0>, 'add_url': u'/admin/sites/site/add/'}], 'has_module_perms': True, 'name': <django.utils.functional.__proxy__ object at 0x02F31E30>, 'app_label': 'sites'}], 'site_url': '/'}]"

**Comment by nitely** [comment]
> I have attached a copy of the settings file.

uhm, where?

Still don't see where the exception comes from. May be you can attach a screenshot of the django traceback (or the real traceback, should be in the console)?

**Comment by Nirmalatatikonda** [comment]
looks like i dont have write permission to the repository to add attachments.

**Comment by nitely** [comment]
Use http://pastebin.com

**Comment by Nirmalatatikonda** [comment]
here is a copy of settings file.
http://pastebin.com/vMdgqxUu

**Comment by nitely** [comment]
Replace:

```python
TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.contrib.messages.context_processors.messages",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.static",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
    "django.core.context_processors.tz",
    "mezzanine.conf.context_processors.settings",
    "mezzanine.pages.context_processors.page",
)
```

by:

```python
TEMPLATES[0]['OPTIONS']['context_processors'].extend([
    "mezzanine.conf.context_processors.settings",
    "mezzanine.pages.context_processors.page",
])
```

**Comment by Nirmalatatikonda** [comment]
that worked. Thanks for the prompt help on all the issues reported so far. really appreciate the support.

**Comment by nitely** [comment]
Great! :smile: 

I'm glad to help. Closing this.
