### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ghost** [nitely/Spirit#86]
Hi;

I think u  must adding option multi language :

English - Arabic - Spanish ... etc

So u just create this option and every one who use Spirit he'll set his language and give u the translation of language so u add it to ur project.

thank u :)

**Comment by nitely** [comment]
Django should auto detect the language based on your Browser.
The translation is taking place at [transifex](http://community.spirit-project.com/topic/21/translations/).

**Comment by sirex** [comment]
@nitely could you please approve requests to join Lithuanian translators team on trasiflex?
https://www.transifex.com/spirit-project/spirit/language/lt/

**Comment by nitely** [comment]
Weird, I don't get an email for new requests. There are other 3 guys asking to join the team (kroitus, desper4ado and shookees) should I added them too or is it just you?

**Comment by sirex** [comment]
@nitely I know all of them and they also want to help with translation, so yes please add them too. Thanks.

**Comment by nitely** [comment]
Great, done!

2016-03-10 4:12 GMT-03:00 sirex <notifications@github.com>:

**Comment by sirex** [comment]
@nitely could you approve one more member **narunask**?

**Comment by nitely** [comment]
Yep, done!
