### ISSUE TITLE
Is it a better idea to let postgresql handle the primary key?

### ISSUE THREAD

**Issue by searene** [nitely/Spirit#94]
If you use postgresql, creating another category would be a little inconvenient. For example, with the following two lines in a test, django will complain `django.db.utils.IntegrityError: duplicate key value violates unique constraint "spirit_category_category_pkey" DETAIL:  Key (id)=(1) already exists.`

    from spirit.core.tests import utils
    self.category = utils.create_category()

Because spirit has already inserted two other categories by default, with respective `id` specified. In the file `spirit/category/migrations/0002_auto_20150728_0442.py`, you can find the following lines:

    if not Category.objects.filter(pk=settings.ST_TOPIC_PRIVATE_CATEGORY_PK).exists():
        Category.objects.create(
            pk=settings.ST_TOPIC_PRIVATE_CATEGORY_PK,
            title="Private",
            slug="private",
            is_private=True
        )

    if not Category.objects.filter(pk=settings.ST_UNCATEGORIZED_CATEGORY_PK).exists():
        Category.objects.create(
            pk=settings.ST_UNCATEGORIZED_CATEGORY_PK,
            title="Uncategorized",
            slug="uncategorized"
        )

It's not hard to fix the problem, you just need to restart the last_value.

    alter sequence spirit_category_category_id_seq restart with 3

But I think it may be convenient if `pk` was not specified in the first place, .i.e. let postgresql generate the suitable `id` for the table. Removing the following two lines in the above code would be better, I think.

    pk=settings.ST_TOPIC_PRIVATE_CATEGORY_PK,
    pk=settings.ST_UNCATEGORIZED_CATEGORY_PK,

**Comment by nitely** [comment]
Migrations are run once, so the issue should not even exist (except if you
re-run that especific migration).

Also, Spirit must know what the private and uncategorized categories pk
are, in order to work properly. Removing the pk in the migration may lead
to weird issues later, this way you know the private category doesn't match
the one in the settings.

**Comment by nitely** [comment]
> from spirit.core.tests import utils
> self.category = utils.create_category()

I didn't pay attention to this before replying.

Are you using a empty db (no migrations ran) for the tests?

**Comment by sirex** [comment]
Same here. I'm migrating data from an old forum and have this duplicate key error.

I think, instead of hardcoding ids, better idea to have a `unique=True` CharField on category, where you can specify a name and use that name in code instead of relying on primary keys.

**Comment by nitely** [comment]
If you need to create categories programmatically, then create a form instance and save it instead of calling `Category.objects.create`.

**Comment by searene** [comment]
Yes, it's a test, with an empty database and no migrations ran. These are the steps to reproduce the error:

1. Create a new database called `spiritdb` in postgresql
2. Change the database settings in `example/project/settings/test.py` to the following lines:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'spiritdb',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '',
    }
}
```

3. Create a new file called `tests.py` under `example`, with the following code:

```python
from django.test import TestCase
from django.core.cache import cache
from spirit.core.tests import utils

class DemoTest(TestCase):
    def test_create_category(self):
        cache.clear()
        self.category = utils.create_category()
```

4. Modify `runtests.py` to search the `example` directory:

```python
test_runner = DiscoverRunner(top_level='example')
failures = test_runner.run_tests(['example'])
```

5. Run the `runtests.py` file

```
./runtests.py example
```

Then you will get the error:

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "spirit_category_category_pkey"
DETAIL:  Key (id)=(1) already exists.
```

**Comment by sirex** [comment]
https://docs.djangoproject.com/en/1.8/topics/serialization/#natural-keys

**Comment by nitely** [comment]
@searene , ok. I'll likely save the keys into the dynamic configuration.

Although, that was something I was trying to avoid since it'd be possible to update the keys from the admin ui which is arguably more insecure than the `settings.py`.

**Comment by nitely** [comment]
I've been digging this further. `ST_UNCATEGORIZED_CATEGORY_PK` is not being used anywhere (except for some unit test), so it can be safely removed.

I think I could just create the private category without passing the pk, then check the returned pk matches `ST_TOPIC_PRIVATE_CATEGORY_PK`, if it doesn't then raise an exception telling the user to set `ST_TOPIC_PRIVATE_CATEGORY_PK` to whatever the returned pk is.

Also, check if the category exists (ie: re-running the migration), if it does then check the title is `Private`, if it's not then create the category and raise the exception again. The user can later remove any category in case she assigned the wrong value to `ST_TOPIC_PRIVATE_CATEGORY_PK`.

Most (all?) databases start the auto-increment field from 1, so `ST_TOPIC_PRIVATE_CATEGORY_PK = 1` should usually work without issues.

**Comment by nitely** [comment]
All done. Closing this.

**Comment by sirex** [comment]
@nitely migrations does not work after removing `ST_TOPIC_PRIVATE_CATEGORY_PK`.

```
django/test/runner.py|370| in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
django/db/backends/base/creation.py|368| in create_test_db
    test_flush=not keepdb,
django/core/management/__init__.py|120| in call_command
    return command.execute(*args, **defaults)
django/core/management/base.py|445| in execute
    output = self.handle(*args, **options)
django/core/management/commands/migrate.py|222| in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
django/db/migrations/executor.py|110| in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
django/db/migrations/executor.py|148| in apply_migration
    state = migration.apply(state, schema_editor)
django/db/migrations/migration.py|115| in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
django/db/migrations/operations/special.py|183| in database_forwards
    self.code(from_state.apps, schema_editor)
spirit/category/migrations/0002_auto_20150728_0442.py|25| in default_categories
    pk=private_category.pk))
ValueError: ST_TOPIC_PRIVATE_CATEGORY_PK setting does not matches the private category. The expected value was: 1
```

Migrations should never rely on external code, which can be changed.

**Comment by nitely** [comment]
@sirex 

> migrations does not work after removing ST_TOPIC_PRIVATE_CATEGORY_PK.

According to the traceback you did not remove it, you changed it to something other than the expected value (1) [which is the default](https://github.com/nitely/Spirit/blob/b133430866790bca026107c65b36493bfce9870d/spirit/settings.py#L9).

> Migrations should never rely on external code, which can be changed.

All Spirit data migrations are idempotent, you can fix the error and run them again.
